### PR TITLE
<Accordion/> - fix item header on hover

### PR DESCRIPTION
**Pull request by daugerdas**
### 🔦 Summary

Fix `<Accordion>` header background color on hover when `<Accordion hideShadow skin="light">`

Description: [DSM-772](https://jira.wixpress.com/browse/DSM-772)

Currently (header on hover):
image

With this change (header on hover):
image

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6883/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6883

**Comment by daugerdas** [comment]
@milkyfruit could you review this change?

**Review by milkyfruit — APPROVED** [review]
@mykas @daugerdas looks great!

**Review by mykas — APPROVED** [review]

**Pull request merged**
