### PR TITLE
fix: inputarea has wrong error icon

### PR DESCRIPTION
**Pull request by smokokoi**
https://github.com/wix/wix-style-react/issues/1144

I took the icon used in InputErrorSuffix.js for Input component and used in InputArea with the styling used in Input component.

### CODE REVIEW

**Comment by lbelinsk** [comment]
Sounds reasonable to me, but it needs to be approved by @wuwa or @milkyfruit

**Comment by lbelinsk** [comment]
@smokokoi

**Comment by lbelinsk** [comment]
Other than that it looks great

**Comment by milkyfruit** [comment]
The error icon looks good, now.

**Pull request merged**
