### PR TITLE
<RichTextArea/> - Support React 16

### PR DESCRIPTION
**Pull request by rghorbani**
### What changed

1. Updated dependencies (`slate`)
2. Added new dependencies (`slate-html-serializer`, `slate-react`)
3. Updated `RichTextArea` module with new `slate` APIs
4. Updated package.json peerDependencies config

### Why it changed

Added support for React 16 with react 16 supporting packages
Answer to #2238 

---

- [x] Change is tested
- [x] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by shlomitc** [comment]
the build is failing for lint error
`1:9  error  'Value' is defined but never used. Allowed unused vars must match /^_$/  no-unused-vars`

**Comment by rghorbani** [comment]
Hi @shlomitc,
Fixed the lint bug two problems:

1. I think the htmlSerializer test needs to change.
2. According to docs this shouldn't be a problem but (TypeError: Cannot read property 'text' of undefined - src/RichTextArea/RichTextArea.js:318).

**Comment by rghorbani** [comment]
Now everything works fine but tests do not pass. I couldn't figure out whats wrong with it.

**Comment by shlomitc** [comment]
Hey. Thanks for the hard work and sorry for the long time to respond.
I'm not too familiar with this component, but it was a good chance to dive deep and try to assist here.

I started to follow the path of one of the failing test - `should call callback on change`.

1. The initial rendering works well.
1. When `driver.enterText` is called, a re-rerendering of the component happens, so `componentWillReceiveProps` is called.
1. It checks that the `value` prop has changed and calls `this.state.editorValue.change().insertText(props.value)`.

At this point, `insertText` looks for the parent of the current range from markers `var parent = document.getParent(start.key);` which returns `null` (node_modules/slate/lib/slate.js:4132)

From here things starts to get wrong and eventually it re-runs the set of rules defined in `htmlSerializer` (error is thrown when reaching line 43 `nodes: next(el.childNodes)`)


So I don't know yet where is the point responsible for it - the schema? the markers? are you familiar with it somehow? hope it helped a bit

**Comment by rghorbani** [comment]
@shlomitc Really thanks.
Hi @nirhart, @artur-charcenko 
As original creators of this component could you provide some help?

**Comment by hepiyellow** [comment]
@rghorbani 
Is this still WIP?

**Comment by rghorbani** [comment]
@hepiyellow Hi,
`slate` package have changed drastically and the changes have messed up the tests.
both me and @shlomitc did tests and could not figure out the problem but it is a good reference for any one who can figure out the problem.
But let me rebase it to check with the new code.

**Comment by shlomitc** [comment]
@rghorbani 
This PR is pending for a while now but I know it's important. We tried continuing it, but there are too many issues to solve.

Our current plan is to recreate this component using Facebook's [Draft.js](https://draftjs.org/) which is lighter, simple and of-course supports React 16. It will also fix many [bugs](https://github.com/wix/wix-style-react/issues?q=is%3Aopen+is%3Aissue+label%3ARichTextArea) in the component.

I'll keep you posted and be happy if you could test the new component when it's out

**Comment by shlomitc** [comment]
@rghorbani I'm thrilled to announce that we created a new component called `RichTextInputArea` - the new generation of the `RichTextArea`. It is based on `Draft.js` which is might lighter and fully supporting React 16.

We're in the very final stages of fixing some edge cases, but feel free to start using it. We'll be happy to get some feedback and if you have any problems - please create an issue.

Thanks for the hard work and patience!

**Pull request closed without merging**
