### PR TITLE
[wix-style-react] - VanillaTestkitParams.wrapper: `HTMLElement` -> `Element`

### PR DESCRIPTION
**Pull request by sidoruk-sv**
### 🔦 Summary

From @testing-library/react@11.2.1 `render()` function returns Element instead of HTMLElement, and any developer that use both @testing-library/react@^11.2 and WSR testkits will got TS error for types mismatch:
https://github.com/testing-library/react-testing-library/releases/tag/v11.2.1

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by sidoruk-sv** [comment]
Related conversation in Slack: 
https://wix.slack.com/archives/C39FTGUBZ/p1605785920376600

**Comment by sidoruk-sv** [comment]
@EgoziE thanks) don't understand why I loose GPG signing for my commits (was able to do that before))

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6599

**Comment by EgoziE** [comment]
@sidoruk-sv I gave you one free pass, on me 😜

**Pull request merged**
