### PR TITLE
Icons added: Brush and List

### PR DESCRIPTION
**Pull request by ChenRoth**
### What changed

added 2 icons for the use of ecom Product Options

### Why it changed
these are the icons designed by our UX
---

- [X] Change is tested
- [X] Change is documented
- [X] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by ChenRoth** [comment]
this was discussed with Domas, and he in turn had a discussion with Noam in ecom
still waiting for a final confirmation from benben or domas

**Comment by argshook** [comment]
@milkyfruit hey, any news about this?

**Comment by milkyfruit** [comment]
I and Noam Raz agreed to keep these icons on e-com code base and not include to WSR for now.

**Comment by argshook** [comment]
alrighty then, closing until further notice

**Pull request closed without merging**
