### PR TITLE
<PopoverMenuItem/> & <TableActionCell/> - disable menu items

### PR DESCRIPTION
**Pull request by Wo1v3r**
### What changed
Added `disabled` prop and behavior to PopoverMenuItem
Added `disabled` prop to secondary actions in TableActionCell
...

### Why it changed

Needed for Price Quotes Web project
...

---

- [ ] Change is tested
- [ ] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by Wo1v3r** [comment]
Please don't merge yet, WIP.

@shlomitc  @argshook  Do you guys think we should also render disabled state for the secondary actions which are not rendered in the popover menu ?

Or it's weird just to put such actions visible at all.

**Comment by shlomitc** [comment]
According to Ben's review - it should remain visible but disabled.

**Comment by Wo1v3r** [comment]
@shlomitc  OK great. So what changes would you like me to make except for adding relevant tests?

**Comment by shlomitc** [comment]
I think this PR is good. The only thing missing is a test for the `TableActionCell` getting a disabled item.

**Comment by Wo1v3r** [comment]
@shlomitc  Added a test similar to the one in popover menu, lmk wdyt.

**Pull request merged**
