### PR TITLE
<SideMenu/> - fix infinite loop when using React 16

### PR DESCRIPTION
**Pull request by banuni**
### What changed
Removed the `setState` inside `shouldComponentUpdate`
...

### Why it changed
Because it created an infinite loop (breaks React16 specifically)
...

---

- [v ] Change is tested
- [ ] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by hepiyellow** [comment]
FYI: You are welcome to open PRs as branches in wix-style-react.

**Comment by hepiyellow** [comment]
Did you really reproduce an infinite loop?
oh, and could you add a test for this?

**Comment by shlomitc** [comment]
@banuni - did you see this also in the React 15 usage or only in React 16?

**Comment by banuni** [comment]
Only on React16, that's since the lifecycle is slightly different. I've
discussed this with Erez face to face on Wednesday.

**Pull request merged**
