### PR TITLE
Add Calendar icon

### PR DESCRIPTION
**Pull request by yakirn**
- [x] Explain what has changed.
I added an icon of a calendar.

- [x] Explain why the change is needed.
It is needed for custom input controls for selecting date, which should behave differently than the normal date picker (e.g dropdown with options: Past year, Past month, Past week, etc).

- [x] Added tests.
No tests are needed.

- [x] Update documentation.
Documentation for icons is autogenerated.

- [ ] Merge master with no conflicts.
- [ ] Make sure the build is passing on ci.
- [x] If this pr closes any issue, please add a github link to close it.
No related issues.

- [x] If you changed something in the product design/UX, you got the approval of [Ben Benhorin](https://wix.slack.com/messages/@benb).
Will do next Sunday.

### CODE REVIEW

**Comment by argshook** [comment]
also, please do not push yarn.lock

**Comment by yakirn** [comment]
@lbelinsk @argshook  OK, on it. thanks!

**Comment by nirhart** [comment]
Its probably a bad export option, please ask your ux to export it differently

**Comment by yakirn** [comment]
@nirhart I asked my UX, she doesn't know how to export it correctly, And I don't see any different from other SVGs in the project. If you can give more specific instruction it would really help.
I tested the SVG on my project (after `yarn link wix-style-react`) and the icon is looking good, so the display in the icons screen is the only thing that is blocking us.
BTW, I got the approve from Ben Benhorin, 
I'm attaching the latest version of the SVG and a screenshot of the icon in my project.
screen shot 2017-09-18 at 12 36 48

**Comment by yakirn** [comment]
I updated the branch with a fresh version of the icon. Working great in my project using `yarn link wix-style-react` but not in the wix-style-react's storybook.

**Pull request merged**
