### PR TITLE
dropdown missing default state EE-29772

### PR DESCRIPTION
**Pull request by urig-wix**
The dropdown should have 0.6 opacity on the border in the default state, that turns to 1 opacity on hover/focus. Specs:

https://zeroheight.com/7sjjzhgo2/p/05a744-05-selections/b/817d21

### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6887/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6887

**Review by jonathanadler — COMMENTED** [review]
@urig-wix  looks great!
Can you ask @johannaasseraf to review?
https://bo.wix.com/pages/wix-ui-tpa.pr_6887/

**Comment by johannaasseraf** [comment]
@urig-wix @jonathanadler looks good :)

**Pull request merged**
