### PR TITLE
Icons added: New Folder and Rename

### PR DESCRIPTION
**Pull request by kelyar**
### What changed
These are two icons we need for new MediaManager.
Icons
...

### Why it changed

...

---

- [ ] Change is tested
- [ ] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by kelyar** [comment]
What's the procedure for adding new icons?
Is it OK to push in WSR?
I saw that icons are being moved to wix-ui-icons-common, should I do PR there instead?

**Comment by shlomitc** [comment]
@kelyar - please add to both wsr and wix-ui-icons-common.
@milkyfruit - are these icons approved?

**Comment by kelyar** [comment]
I believe these icons are not approved yet, it's just what I got from designer

**Comment by milkyfruit** [comment]
Hi, design wise they are ok, they look pixel perfect.
The SVG files are not clean, though.
I optimised the files and added them here:

**New Folder.svg**
```
<svg xmlns="http://www.w3.org/2000/svg" width="17" height="18" viewBox="0 0 17 18">
  <path d="M1,4 L1,17 L16,17 L16,4 L1,4 Z M6.5,3 L17,3 L17,18 L0,18 L0,0 L5,0 L6.5,3 Z M9,10 L9,7 L8,7 L8,10 L5,10 L5,11 L8,11 L8,14 L9,14 L9,11 L12,11 L12,10 L9,10 Z M4.38196601,1 L1,1 L1,3 L5.38196601,3 L4.38196601,1 Z"/>
</svg>
```

**Rename.svg**

```
<svg xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 15 14">
  <path d="M0,2 L0,5 L1,5 L1,2 C1,1.44771525 1.44771525,1 2,1 L7,1 L7,13 L4,13 L4,14 L11,14 L11,13 L8,13 L8,1 L13,1 C13.5522847,1 14,1.44771525 14,2 L14,5 L15,5 L15,2 C15,0.8954305 14.1045695,-2.02906125e-16 13,0 L2,0 C0.8954305,2.02906125e-16 -1.3527075e-16,0.8954305 0,2 Z"/>
</svg>
```

**Comment by kelyar** [comment]
Thanks! I've updated icons in PR.
I will also add updated icons in wix-ui-icons-common later today.

**Comment by milkyfruit** [comment]
Thanks @kelyar, please don't add these icons to Wix-UI repo yet. I'll give a version with 24x24px canvas.

**Comment by argshook** [comment]
thanks!

**Pull request merged**
