### PR TITLE
Custom suffix in TimePicker

### PR DESCRIPTION
**Pull request by DanielEliraz**
Adding ability to add custom suffix before the ticker and after the am-pm component if it is displayed.

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [x] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [X] Story
  - [X] API description
- 🔬 Change is tested
  - [X] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by EgoziE** [comment]
Can you send a link to your zeplin spec?

This is our Time Picker zeplin spec:
https://zpl.io/VqWdqKl

**Ayelet Reuveni** is our UR responsible for this component, please make sure changes are approved and are aligned in our zeplin, it's important to us.
Thanks

**Comment by DanielEliraz** [comment]
@EgoziE, I think that the spec that you sent me is for the new TimePicker you talked about. For example, the current one has width of 120px, while the one in the spec has 115px.
I tried to be coherent with the current specs in order not to break any existing time picker.

Our Zeplin spec: https://zpl.io/251l9EQ
By the way how can I get permission to the applitool?

@orgol99, FYI

**Comment by EgoziE** [comment]
There are no 2 specs, only this one.
All I'm saying is that both our UXs should talk and decide what's the component behavior and looks.
Then our zeplin should be adjusted accordingly.
and only then we can talk about development.

**Comment by DanielEliraz** [comment]
Hi @domasmart,
I need credentials to applitools in order to see the differences between my version and the origin one.
Are you able to provide it to me?
Thenks

**Comment by EgoziE** [comment]
I'm closing this PR just for the moment.

@milkyfruit can you please take a look at this design, this is not aligned to what we have.

**Comment by DanielEliraz** [comment]
Hey @milkyfruit 
AFAIK you talked to Yansou and approved the design, can you please note it here?

**Comment by orgol99** [comment]
Hi,

The design was approved by Domas.

Thanks!

**Comment by milkyfruit** [comment]
@EgoziE @danielleraiz @orgol99 yes, TimePicker should support affixes following the same input logic: https://zpl.io/V11YZWm (please scroll till contraints)

**Comment by DanielEliraz** [comment]
Great, I opened new PR: #5097

**Pull request closed without merging**
