### PR TITLE
fixed hover for accordion with skin="light" and hideShadow="true"

### PR DESCRIPTION
**Pull request by Oripi**
### 🔦 Summary

fixed hover for accordion with skin="light" and hideShadow="true"
fixes issue #DSM-614

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [x] Visual test

### CODE REVIEW

**Comment by EgoziE** [comment]
Hey @Oripi thanks for contributing
In your PR you just forced bg to be initial regardless any state, which might work, but reading the code makes it really hard to understand why was this behavior introduced.

I think a better solution is to change the current bg according to state, something like:
```diff
-  .root:not(:disabled):hover .header {
+  .root:not(:disabled):not(:hideShadow):hover .header {
```

**Comment by Oripi** [comment]
no, i only forced initial when there's `:shadow` on the css, i think you copied the wrong line

**Comment by Oripi** [comment]
`.root:open:skin(light):hideShadow .header {`

**Comment by EgoziE** [comment]
Fine, we'll keep it as is

**Pull request merged**
