### PR TITLE
WIP: <Box /> - new feature gap

### PR DESCRIPTION
**Pull request by mykas**
This is still WIP it will be explained a bit in a separate RFC issue.

### CODE REVIEW

**Comment by nitayneeman** [comment]
I think we should discuss in the RFC before implementing and also compare the pros/cons compared to the `Layout` component

**Comment by mykas** [comment]
I agree. Created this just an example in RFC issue.

**Comment by shlomitc** [comment]
@nitayneeman - so what's your opinion regarding this?
We also have an old issue suggesting something similar
https://github.com/wix/wix-style-react/issues/2990

**Comment by nitayneeman** [comment]
At first I thought that we should not complicate `Box` for something that's currently possible with the Layout.

But, it seems that `gap` is going to be supported natively by `flexbox` in the near future: https://youtu.be/-oyeaIirVC0?t=820

It's already available in FF:
https://developer.mozilla.org/en-US/docs/Web/CSS/gap#Support_in_Flex_layout

This means the approach is to let the flex container to own and determine the spacing of the children. It's nice to see this demand also comes from the community - so that's why I think this feature is reasonable. 

I guess this PR became the RFC issue? 🤨

**Comment by mykas** [comment]
Sorry, I just could not find the right time to open RFC :/

**Comment by shlomitc** [comment]
So... do we plan to continue with this PR? @nitayneeman what do you suggest?

**Comment by nitayneeman** [comment]
> So... do we plan to continue with this PR? @nitayneeman what do you suggest?

@mykas are you going to continue with the RFC you've planned soon?

If not, I suggest closing this PR in the meantime and prioritize a task in the backlog of this feature (we can also keep it for a guild week but we need to refine a solution before).

**Comment by shlomitc** [comment]
So I'm closing this PR for now, it's Passover cleaning time.
@mykas - if you get some time to work on it or find someone who can contribute - please reopen

**Pull request closed without merging**
