### PR TITLE
WUT: add testkit folder to `includes` of `tsconfig`

### PR DESCRIPTION
**Pull request by argshook**
`src/testkit` folder contains testkit exports files for multiple
testing platforms. All those files are considered entry points for users
and so all of them should end up in the released package of
`wix-ui-tpa`.

However, only those files that are required by other files ended up in
`dist/src/testkit`.

for example, because some `.spec.js` or `.e2e.js` require
`src/testkit/enzyme.js` or `src/testkit/protractor`, these files end up
properly in `dist/src/testkit`.

`src/testkit/puppeteer.ts`, however, does not. It was not used by any
other file and `tsconfig.json` `includes` array does not have a glob
matching that.

This PR adds a glob to match all `src/testkit/**/*.ts` files, and thus
all of them should appear `dist/src/testkit` as expected

### CODE REVIEW

**Review by jonathanadler — APPROVED** [review]
🚀

**Comment by argshook** [comment]
depends on https://github.com/wix/wix-style-react/pull/6997

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6998/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6998

**Pull request merged**
