### PR TITLE
<PopoverMenu/> - change divider to ListItemSection internally

### PR DESCRIPTION
**Pull request by EgoziE**
Fix accessibility issues with dividers inside PopoverMenu

### CODE REVIEW

**Comment by EgoziE** [comment]
Resolves https://github.com/wix/wix-style-react/issues/5781

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5810/

**Comment by shlomitc** [comment]
It works better now but it's still focusing on the element when navigating with the keyboard.
In `DropdownLayout`, the way to point that an item is not selectable (or navigatable) is one of the following:
1. It is defined explicitly as a [DropdownLayout Divider](https://github.com/wix/wix-style-react/blob/master/src/DropdownLayout/DropdownLayout.js#L334-L336)
2. it is a [disabled item](https://github.com/wix/wix-style-react/blob/master/src/DropdownLayout/DropdownLayout.js#L494)
3. it has a [`title` property](https://github.com/wix/wix-style-react/blob/master/src/DropdownLayout/DropdownLayout.js#L494) on the object

The first option is probably not good in this case, but both the second and third will work. `title` was created specifically for this use-case if I remember correctly


Also - I think that we shouldn't a divider to each one of the examples, it's better just to create a separate example that showcases the divider scenario

**Comment by EgoziE** [comment]
Yes, I took that in mind, it's a global problem in all dropdown family components, I think I'll dedicate a different PR for this issue.

**Pull request merged**
