### PR TITLE
fix(DatePicker): Add empty string as option to set DatePicker value in proptypes

### PR DESCRIPTION
**Pull request by xmityaz**
### What changed

Add possibility to set empty string as value to DatePicker without a console error of violating the proptypes

### Why it changed

When I've tried to reset the datepicker value with null it throws the error:

> prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

If I'm setting it as undefined it tells me to not mess with controlled/uncontrolled `value` prop.

So the only way to see placehoder with controlled value is to set it to empty string, but it throws an errror to console with invalid prop:

> jsWarning: Failed prop type: Invalid prop `value` of type `string` supplied to `DatePicker`, expected `object`.

### CODE REVIEW

**Comment by argshook** [comment]
hm, not sure if this is really an issue. `placeholderText` is displayed if you don't set `value` prop at all.

setting `value: undefined` also works ok for me.
`value` for datepicker should be object, empty string is a workaround.

looks like #1669 fixed this earlier (already released).

closing, please reopen if there's something i missed.

**Comment by argshook** [comment]
@xmityaz 
> And then it impossible to clean up the value back to empty.
this was fixed in latest release, please verify.

**Comment by argshook** [comment]
well im a little slow sometimes. turns out i just fixed locally and forgot to push :)

https://github.com/wix/wix-style-react/pull/1711

should become part of next release

**Comment by argshook** [comment]
i merged https://github.com/wix/wix-style-react/pull/1711 with a fix.

closing this again, feel free to reopen (perhaps as issue) if it still persists.

the reason im not merging this PR because it is a workaround and can even be misleading. DatePicker would look like it supports empty string for no apparent reason, thus bringing confusion, i want to avoid that.

**Comment by xmityaz** [comment]
@argshook works with `undefined`, thanks

**Pull request closed without merging**
