### PR TITLE
Padding issue fix

### PR DESCRIPTION
**Pull request by Shaniko**
### What changed
content.scss : change padding to 30px;
grid.css : (new :not(last-child))
.row:not(last-child) {
        margin-bottom: $grid-row-margin-bottom;
    }
...

### Why it changed
content.scss for some weird reason has $content-padding: 24px 30px 18px;
grid.css - dont add margin when row is he last child
...

---

- [ ] Change is tested
- [ ] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by shlomitc** [comment]
We have [this PR](https://github.com/wix/wix-style-react/pull/1483/files) already, but it maintains the 24px padding-top for the card content.

This is how it looks with 30px padding-top:
image


@wuwa - which one is the correct one?

**Comment by Shaniko** [comment]
Can u please consult with the UX guys :)

**Comment by wuwa** [comment]
should be like any card - 24px top, 30px left-right-bottom.

**Comment by shlomitc** [comment]
Cool, so I'm closing this PR and getting the second one ready for merge

**Comment by Shaniko** [comment]
Please dont delete or close this issue
the padding you are talking about should be fixed right now.
Please find the attached screen shot and understand the change, and padding-top should be updated only if there's a header, only then, 24px, so add this to my change.

image
g)

**Comment by shlomitc** [comment]
@Shaniko - As I wrote in my comments - I closed the PR in order to get the other PR ready for merge and release which was done today.
https://github.com/wix/wix-style-react/blob/master/CHANGELOG.md#2032---2018-03-22

As @wuwa wrote - grid padding should be 24px from the top, and this is the guideline we are going with. If it should behave

**Comment by shlomitc** [comment]
are you talking about the case when there is a `Card` with no divider?
image

**Comment by argshook** [comment]
closing, because it has been fixed since Mar 22 in https://github.com/wix/wix-style-react/commit/6940af88f

**Pull request closed without merging**
