### PR TITLE
`<Table.Loader>` - added component

### PR DESCRIPTION
**Pull request by dorduch**
### 🔦 Summary
...

### ✅ Checklist
- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by shlomitc** [comment]
@wuwa - can you please review?
https://wix-wix-style-react-pr-3372.surge.sh/?selectedKind=Components&selectedStory=Table&full=0&addons=0&stories=1&panelRight=0
see the "Table Loader" example

**Comment by shlomitc** [comment]
@wuwa - AFAIK, the table height is defined by its content, meaning if there are no items - it doesn't get any height.
Maybe in real layout, the table should be rendered in a stretched card that takes the entire screen height, but then the loader will not be centered, just at the top

**Comment by wuwa** [comment]
@shlomitc i don't think we can count on full height card stretch. is there a way to give it min height according to expected items height?

**Comment by shlomitc** [comment]
@wuwa - this might still cause a "jump" between the loader and the actual size. I guess we can set something up if this is the required behavior

**Comment by shlomitc** [comment]
@dorduch @wuwa - what do you guys suggest?

**Comment by wuwa** [comment]
can card (containing the table) be set to have min-height in px?

**Comment by shlomitc** [comment]
@wuwa - I don't think it's built in. I guess this can be added with this feature as well if defined well

**Comment by shlomitc** [comment]
It's been hanging for a while now. I'm closing and we'll reopen once we work on it

**Pull request closed without merging**
