### PR TITLE
extract wix-style-react perfer to dedicated package

### PR DESCRIPTION
**Pull request by argshook**
This PR extracts `wix-style-react test7:performance` script into a dedicated package.

in other words
```diff
-packages/wix-style-react/.perfer/package.json
+packages/wix-style-react-test-perfer/package.json
```

why?

in falcon a folder with `package.json` in it is considered package and
so falcon and yoshi tries to treat it as such.

However, in current state this was not really a package, not registered
in `lerna.json`, not in an appropriate location and used as a workaround
for `yoshi build` to have a separate `dist`.

These issues can be workaround but instead of that it's cleaner and just
easier to treat perfer test as a separate package.

Additional benefit is cleaner `scripts` section in `wix-style-react/package.json`

`perfer.config.js` still remains in same place, so there's no impact on
the usage

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6933/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6933

**Review by mykas — APPROVED** [review]
Nice!

**Comment by argshook** [comment]
one unrelated wix-ui-tpa visual test is faling, otherwise good to merge

**Pull request merged**
