### PR TITLE
MusicalNote icon added

### PR DESCRIPTION
**Pull request by kelyar**
## Before you request a review, please make sure to check the following boxes:

looks like this

- [ x] This is the new MusicalNote icon
- [ x] We need it in our Wix Video Maker project
- [ ] Added tests.
- [ ] Update documentation.
- [ x] Merge master with no conflicts.
- [ ] Make sure the build is passing on ci.
- [ ] If this pr closes any issue, please add a github link to close it.
- [ ] If you changed something in the product design/UX, you got the approval of [Ben Benhorin](https://wix.slack.com/messages/@benb).

### CODE REVIEW

**Comment by lbelinsk** [comment]
is this approved by Ben? 
@wuwa

**Comment by lbelinsk** [comment]
@kelyar please update when it get's approved

**Comment by kelyar** [comment]
@lbelinsk sure, I'm waiting for new icon now

**Comment by kelyar** [comment]
@lbelinsk Got the approval, icon is updated.

**Pull request merged**
