### PR TITLE
add tree shaking

### PR DESCRIPTION
**Pull request by lbelinsk**
Should be merged together with https://github.com/wix/yoshi/pull/727

### CODE REVIEW

**Comment by argshook** [comment]
does it really work? no more `import Thing from 'wix-style-react/Thing'` and we keep `index.js`?

Last time this was tried (~year ago) it didn't work and `npm install wix-style-react` got considerably larger

screenshot 2017-11-23 17 57 25

it was reverted in the end. But maybe it's all good this time?

**Comment by lbelinsk** [comment]
@argshook I made sure that it truly works!
Moreover, we have an alpha version `version_tree-shaking` which is being used by some guineapig project for more than 2 months, and they didn't complain about anything.

This pr will disable the lint rule in yoshi: https://github.com/wix/yoshi/pull/727

**Comment by argshook** [comment]
awesome, this is great news!

i guess soon i'll be able to change import example in story pages

**Comment by lbelinsk** [comment]
Yes, but first let's see that we have no complaints from the consumers.
The main `index.js` file is updated to expose everything, so after yoshi's pr will be merged we can merge this.

**Pull request merged**
