### PR TITLE
<Text/> - UniDriver remove react base

### PR DESCRIPTION
**Pull request by mosheKerbel**
use 'new' uniDriver functions which makes the usage of ReactBase redundant.

### CODE REVIEW

**Comment by mosheKerbel** [comment]
@shlomitc

**Comment by shlomitc** [comment]
What’s the benefit of it?

**Comment by mosheKerbel** [comment]
use this function in e2e, currently it's supported in jsdom env. only

**Comment by mosheKerbel** [comment]
> What’s the benefit of it?

use this function in e2e, currently it's supported in jsdom env. only 
@shlomitc

**Comment by shlomitc** [comment]
Awesome

**Pull request merged**
