### PR TITLE
<PageHeader /> BackButton support - RTL

### PR DESCRIPTION
**Pull request by Shaniko**
### 🔦 Summary

A small css update - to support RTL:
Support the back-button to be aligned correctly.
Add small space between action buttons

### ✅ Checklist

- 📚 Change is documented
  - [x] Story

### CODE REVIEW

**Comment by Shaniko** [comment]
A small css update - to support RTL:
Support the back-button to be aligned correctly.
Add small space between action buttons

**Review by TalZa1810 — CHANGES_REQUESTED** [review]
Please add visual tests. Also note that 20 visual tests were failed. 
I would use `dir=rtl` instead of adding the same class. We have multiple examples for rtl within the library that you can use as a reference.

**Comment by Shaniko** [comment]
Hey.
Thanks for your comments and for your help.
Here is the problem this PR is trying to resolve:

image

**Comment by TalZa1810** [comment]
Duplication of - https://github.com/wix/wix-style-react/pull/5956

**Pull request closed without merging**
