### PR TITLE
<CounterBadge /> Add "light" skin

### PR DESCRIPTION
**Pull request by xmityaz**
### 🔦 Summary
New skin for the CounterBadge component. The image below to see the look

Screen Shot 2020-09-18 at 7 55 54 PM

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_6003/
* https://preview.wix-style-react.com/pr_6003

**Comment by EgoziE** [comment]
@xmityaz Thanks for the contribution
I don't see a light skin in our Zeplin, who was the UX from our team that approved it?

**Comment by xmityaz** [comment]
> @xmityaz Thanks for the contribution
> I don't see a light skin in our Zeplin, who was the UX from our team that approved it?

Our designer approved it with Domas Markevičius. Not sure if Domas in github to tag him

**Review by milkyfruit — CHANGES_REQUESTED** [review]
@EgoziE all good I approved this. The skin is added now to the specs.

@xmityaz the skin name should be renamed to `neutralStandard`, to make it aligned with Badge and BadgeSelect components.

**Pull request merged**
