### PR TITLE
<Modal /> - story updates according new storybook guidelines

### PR DESCRIPTION
**Pull request by egidijusja**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6843/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6843

**Review by milkyfruit — CHANGES_REQUESTED** [review]
- [ ] 1st example — please change border width to 2px
- [ ] 2nd example — please change close button to this:
```
<TextButton onClick={closeModal} underline="always" skin="light">
        Close Modal
      </TextButton>
```
- [x] 3rd example — please fix overflow issue when calendar is open. Make it all visible when open.

The rest is great!
@egidijusja

**Review by milkyfruit — APPROVED** [review]

**Review by mykas — APPROVED** [review]
Looks super good!

**Pull request merged**
