### PR TITLE
Checkbox component- adding focus-ring

### PR DESCRIPTION
**Pull request by barboaron**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by barboaron** [comment]
Merge this PR only after this PR: https://github.com/wix/wix-ui/pull/2038 is merged.

**Review by nitayneeman — COMMENTED** [review]
It looks good!

But I think we should test it somehow, we could do it with E2E (like in RadioButton) but probably a visual test will be better.
Can you add a test please?

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6769/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6769

**Review by nitayneeman — APPROVED** [review]

**Pull request merged**
