### PR TITLE
use storybook-snapper's config

### PR DESCRIPTION
**Pull request by jonathanadler**
### 🔦 Summary
Adding the use of storybook-snapper to the library.
First by just installing it and using its config.
In the future we can use it to write tests.

### ✅ Checklist
- [ ✅] 👨‍💻 API change is approved by the UI Infra Developers - no api change
- [ ✅] 👨‍🎨 UX change is approved by the Design System UX - no ux change
- 📚 Change is documented
  - [ ❌] Story
  - [ ❌] API description
  - [ ❌] Other (explain) - Should be documented
- 🔬 Change is tested
  - [ ❌] Component
  - [ ❌] Visual test

### CODE REVIEW

**Comment by mosheKerbel** [comment]
@jonathanadler  i couldn't find the repo with the code of `storybook-snapper/config/applitools.config`
could u put a ref?

**Comment by jonathanadler** [comment]
> @jonathanadler i couldn't find the repo with the code of `storybook-snapper/config/applitools.config`
> could u put a ref?

Sure: https://github.com/wix-incubator/storybook-snapper

**Comment by jonathanadler** [comment]
I see that this isn't working at the moment, because it makes the assumption that all tests are async.
I'll make a fix to storybook-snapper and I hope it will fix this.

**Comment by jonathanadler** [comment]
I think this should be OK now

**Comment by mykas** [comment]
Moved this to another pr and merged! :) now we have snapper config and use it on ImageViewer and SocialPreivew visual tests.

**Pull request closed without merging**
