### PR TITLE
update InputErrorSuffix => dynamic tooltip place

### PR DESCRIPTION
**Pull request by Shaniko**
### What changed
Input => for some reason index calls InputErrorSuffix
So I've updated InputErrorSuffix to send this prop too

...

### Why it changed
placement="top" => placement={this.props.placement || this.props.tooltipPlacement}
...

---

- [ ] Change is tested
- [ ] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by argshook** [comment]
hello, please explain what changed and why.
why do you need to adjust position?
why do you need two props for it?

i also see this includes `warning` icon which was already merged a while ago

**Comment by Shaniko** [comment]
warning icon has not changed from the prev merged.

**Comment by argshook** [comment]
@Shaniko so please do not push it into this PR then. even if you need a new icon, it should be separate PR, let's not mix things

**Comment by Shaniko** [comment]
Changes moved to tooltipLocation branch

**Pull request closed without merging**
