### PR TITLE
git ignore testkit auto generated files

### PR DESCRIPTION
**Pull request by itaytay**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by itaytay** [comment]
@argshook - this PR is instead of #4829. This time I only removed the auto generated files as you wrote in the mentioned PR.
Please let me know if something else still needs to be changed. Thanks

**Comment by itaytay** [comment]
Closed this PR because tests still fail - can't generate the files.

**Comment by argshook** [comment]
you can leave PR's open, we can do ongoing fixes

**Comment by itaytay** [comment]
I don't want PRs that are on hold to add noise to the open PRs list.
If I'll get back to it in a reasonable time I'll reopen this one

**Pull request closed without merging**
