### PR TITLE
<DataTable/> - style attribute gets to render array

### PR DESCRIPTION
**Pull request by mykas**
This PR fixes an issue introduced in DataTable, where style attribute gets map() method third argument.

### CODE REVIEW

**Comment by NitayRabi** [comment]
I think @liorur Added the style for a reason - we might want to pass it in case of virtualisation

**Comment by mykas** [comment]
True, thats why I'll show him this PR.

**Comment by mykas** [comment]
@liorur any comments on this?

**Comment by mykas** [comment]
Found a place where he needs to use it: https://github.com/wix/wix-style-react/commit/8a821c5bf2cbf6eb979efe4edfc51de1773206e1#diff-71ae30a4d5d2e610065bc2cb5ad56b68R293

**Comment by mykas** [comment]
I'll add a proper map usage then :)

**Pull request merged**
