### PR TITLE
eyes-storybook: Remove browser limitation + fix concurrency

### PR DESCRIPTION
**Pull request by jonathanadler**
Use latest browsers: this means a lot of tests will break

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6988/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6988

**Review by nitayneeman — APPROVED** [review]
It seems that only 2 are broken:
image

And I think that Dialog is flaky

**Comment by jonathanadler** [comment]
> It seems that only 2 are broken:
> image
> 
> And I think that Dialog is flaky

Very weird 🤔

**Pull request merged**
