### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by kaminskypavel**
### 🔦 Summary
just a small typos in the troubleshooting.md
...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [x ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by EgoziE** [comment]
Hey @kaminskypavel 
Thanks for your PR.
Please make sure not to create PRs from a forked project.
CI will automatically fail with the following message:
```
The user "kaminskypavel" that created this commit is not a member of the repository's organization ("wix"), PR is dangerous, will not run this build.
```

Closing this one.

**Comment by kaminskypavel** [comment]
@EgoziE how would one create a PR?

**Comment by EgoziE** [comment]
Read our contribution guide:
https://github.com/wix/wix-style-react/blob/master/CONTRIBUTING.md

**Comment by kaminskypavel** [comment]
Thanks @EgoziE 

unfortunately I cannot branch :
`remote: Permission to wix/wix-style-react.git denied to kaminskypavel.
fatal: unable to access 'https://github.com/wix/wix-style-react/': The requested URL returned error: 403`

anyways, FWIW, this is a typo fix , you can take it from [here](https://github.com/kaminskypavel/wix-style-react/blob/master/docs/usage/Troubleshooting.md)

**Pull request closed without merging**
