### PR TITLE
<RadioGroup/> - make arrows navigate between radio items

### PR DESCRIPTION
**Pull request by Zivilekin**

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6881/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6881

**Comment by mykas** [comment]
Hey @Zivilekin 🌷 ! Lets have some interactive example in story where we could play around with the keys and also select one of the items.

**Comment by Zivilekin** [comment]
How accessibility works now in RadioGroup:
1. **Tab** moves focus on first radio button of radio group. If it is already focused, focus is moved on the next item (f.e. next radio group, checkbox etc)
2. **Arrows** are for navigating through radio options in single RadioGroup
3. **Space** is for selecting Radio button when it's focused

**Review by mykas — APPROVED** [review]

**Pull request merged**
