### PR TITLE
fix types for PopoverMenu.MenuItem text prop

### PR DESCRIPTION
**Pull request by brumeregan**
component `<PopoverMenu.MenuItem />` should accept prop `text` with type string and Node

### CODE REVIEW

**Comment by EgoziE** [comment]
As far as the design indicates, text should accept only text.
Need to add an Icon? please use prefixIcon prop.

If your design is completely different, let's discuss in the channel with both your UX and ours.
I'm closing this PR for now.

**Comment by mykas** [comment]
@EgoziE you forgot about translation strings which are node based

**Comment by EgoziE** [comment]
@brumeregan would you please provide an example?
Are your translations not text based?

**Comment by EgoziE** [comment]
Ok I got this, will reopen and merge.

**Comment by brumeregan** [comment]
We are implementing Roles&Permissions feature and it was designed like that
Screen Shot 2020-04-21 at 1 58 58 PM

**Pull request merged**
