### PR TITLE
<Tooltip/> - fix testkit for puppeteer

### PR DESCRIPTION
**Pull request by roibWix**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6859/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6859

**Comment by roibWix** [comment]
@EgoziE,
I think this [method](https://github.com/wix/wix-style-react/pull/6859/files#diff-e0f4950f3b6335415e533493ca19569bfe488ce9d6b020cf852b6ed9652c46e3R72) is unnecessary.
It's originally from popover component.
Mouse out event (mouseLeave method) will make the tooltip disappear whether clicking outside of the tooltip does nothing. 
What do you think?

**Comment by EgoziE** [comment]
PR looks good. how did you test it?
About your question, let's leave API as is, people are using it already.

**Comment by roibWix** [comment]
I've tested it locally with an app like a user.
Perhaps I should add e2e, what do you think?

**Comment by EgoziE** [comment]
No need for e2es.

**Review by EgoziE — APPROVED** [review]

**Pull request merged**
