### PR TITLE
`<ModalPreviewLayout/>`- fix test

### PR DESCRIPTION
**Pull request by TalZa1810**
### 🔦 Summary
Fix flaky test

### CODE REVIEW

**Comment by TalZa1810** [comment]
ok, I see now that it still hasn't resolved the issue. There's still a tiny gap which I cannot understand what causes this change:


I think that maybe we should skip this test, add an issue about this and investigate this later. wdyt?

**Comment by shlomitc** [comment]
opening an issue means just sits in the backlog and no one will ever touch it until I close it for inactivity.
So either investigate a bit deeper to see where this issue is coming from, or delete this test and forever hope it will never break

**Comment by mykas** [comment]
Hey @shlomitc , lets remove this test. I don't see the benefit of this except for checking the styling of tooltip. We can already check in unit tests if tooltip appears on hover.

**Comment by TalZa1810** [comment]
ok, I've decided to remove the e2e file and moved the navigation button tests to the visual.js file.

**Pull request merged**
