### PR TITLE
<Text/> - change ellipsis example

### PR DESCRIPTION
**Pull request by EgoziE**
change ellipsis example
image

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5988/

**Comment by shlomitc** [comment]
shouldn't there be a simple example of a one-line ellipsis before the multi-line appears?

**Comment by EgoziE** [comment]
@milkyfruit

**Comment by milkyfruit** [comment]
It seemed the most optimal to make this way, otherwise we would have to show 3 examples.

Now, first example shows text without any props and text with two props. So it should be relatively easy to understand that maxLines doesn't work without ellipsis, but ellipsis work alone. 
Second example starts with text with ellipsis only, which is simple example.

**Comment by shlomitc** [comment]
it's just that you don't need the `maxLines` in order to create a single-line ellipsis. so this is kind of redundant.
It's not critical though

**Comment by EgoziE** [comment]
@milkyfruit Maybe I can change the description to be:

Text component can wrap the text, show ellipsis or do both. Setting `maxLines` prop truncates the text at a specific number of lines (use this prop only when you need to show 2 lines or more).

**Comment by milkyfruit** [comment]
@EgoziE Sounds great, please do it.

**Pull request merged**
