### PR TITLE
<RadioGroup/> - add deprecation message for type="button"

### PR DESCRIPTION
**Pull request by mykas**
This PR removes RadioGroup `type="button"` styling option. To achieve this kind of styling use - `<SegmentedToggle/>`.

### CODE REVIEW

**Comment by shlomitc** [comment]
Maybe we should deprecate instead of removing? I guess there are some people using it

**Comment by mykas** [comment]
Yes, I will probably deprecate it instead. Thought  that maybe I could still jump in to wsr 6 breaking changes wagon.

**Comment by shlomitc** [comment]
Better to leave it to next version. In the meanwhile, just remove proptypes (so it will be removed from story) and add deprecation log.

**Comment by shlomitc** [comment]
this PR will close this issue as well https://github.com/wix/wix-style-react/issues/1545

**Comment by shlomitc** [comment]
@mykas - are you taking care of this?

**Comment by mykas** [comment]
yes, I will continue later this week

**Comment by mykas** [comment]
Hey @shlomitc , I have reverted my previous changes and added deprecation log instead.

**Pull request merged**
