### PR TITLE
[wix-style-react] Add global config for playground components

### PR DESCRIPTION
**Pull request by mykas**

### CODE REVIEW

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7058/

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7058

**Review by shlomitc — COMMENTED** [review]
can you please change one of the stories to stop importing `allComponents` so we know it actually works?

**Comment by mykas** [comment]
I am about to do more then just one story. Stay on

**Review by shlomitc — APPROVED** [review]

**Pull request merged**
