### PR TITLE
`<Tag/>` - remove redundant e2e when we have .visual already

### PR DESCRIPTION
**Pull request by mykas**

### CODE REVIEW

**Comment by mosheKerbel** [comment]
are you sure it's redundant?
take for example this test https://github.com/wix/wix-style-react/blob/bda8d185c8744052f3729f0a064259dc1fd193af/src/Tag/Tag.e2e.js#L79
i don't see it exists in the visual

**Comment by mykas** [comment]
We are not testing tooltip show ups on hover. This should be covered in unit tests.

**Comment by mykas** [comment]
What we could add is just a screenshot that it wen to `...`

**Comment by mykas** [comment]
Actually it can't be covered in unit tests too. So the only way to move this to .visual and se that it goes to `...`.

**Pull request merged**
