### PR TITLE
`<MarketingLayout/>` - changing paddings according to specs

### PR DESCRIPTION
**Pull request by adirou**
### 🔦 Summary
Adding option to present content in full width layout inside MarketingLayout component
...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7076/

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7076

**Comment by adirou** [comment]
@ErezPaperny

**Review by milkyfruit — CHANGES_REQUESTED** [review]
@adirou when `size` is set to `medium` and `large` please set the paddings to 30px:
Now:
image
Should look like:
image

**Comment by adirou** [comment]
> @adirou when `size` is set to `medium` and `large` please set the paddings to 30px:
> Now:
> image
> Should look like:
> image
> 
> This is the link to full spec:
> https://zpl.io/bz37dzl
> 
> @mykas this PR is aligned with me, it's fixing what's implemented incorrectly.

@milkyfruit just in vertical or always?

**Comment by milkyfruit** [comment]
> > @adirou when `size` is set to `medium` and `large` please set the paddings to 30px:
> > Now:
> > image
> > Should look like:
> > image
> > This is the link to full spec:
> > https://zpl.io/bz37dzl
> > @mykas this PR is aligned with me, it's fixing what's implemented incorrectly.
> 
> @milkyfruit just in vertical or always?

@adirou only for `direction="vertical"`

**Review by milkyfruit — APPROVED** [review]
@adirou the change looks great!
@mykas could you merge this pr?

**Pull request merged**
