### PR TITLE
Tooltip fix(react 16)

### PR DESCRIPTION
**Pull request by Faradey27**
### What changed

- fixed tooltip for react 16

### Why it changed

- to support react 16

---

- [x] Change is tested
- [x] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by Faradey27** [comment]
@argshook ping

**Comment by argshook** [comment]
@Faradey27 i went through the usecases that i saw crashing browser and can no longer reproduce
didn't test with react 16 though. otherwise looks ok to me

**Comment by hepiyellow** [comment]
Who asked for this?
This doesn't look like a small trivial fix, so I think we should not make such fixes. WSR is not officially supporting React 16 as far as I know, so it doesn't worth the effort.
We need to test it with React 16 if we want to support it.
@shlomitc ?

**Comment by shlomitc** [comment]
@hepiyellow - this is a request that came from several users and is low in our priority.
As this was a small fix done by Andrii, it was ok from my side to add it while declaring this is not officially supported.

The previous fix caused issues so this attempts to solve them.
So this is kind of a quick win. if it still causes us issue - it will go back to the backlog and won't be fixed until we rewrite the Tooltip logic.

**Comment by hepiyellow** [comment]
Just wanted to mention that Oleg from adi came to me the other day, asking for a fix in Tooltip in WSR with React 16, and I finally recommended him do use `wix-ui-adi`, which he found satisfying.
Just wanted to make sure that we offer to use wix-ui-core (and derived libraries) when it comes to React 16.

**Comment by Faradey27** [comment]
@shlomitc so what the correct approach here? should we close pull? or merge(build is green)

**Comment by shlomitc** [comment]
merge

**Comment by shlomitc** [comment]
@argshook - did you test it on a React16 project?

**Comment by argshook** [comment]
@shlomitc no, i was more interested in not breaking v15. it doesn't so im okay with it :)

**Comment by ipanasenko** [comment]
Doesn't work with React16. No errors, no tooltip. It just doesn't show, that's all

**Pull request merged**
