### PR TITLE
Underline Style doesn't work on TextLink in storybook

### PR DESCRIPTION
**Pull request by iaroslavshvets**
Underline Style doesn't work. When Underline style is on, the underline must be always visible

### CODE REVIEW

**Comment by nirhart** [comment]
You changed a prop name, it will break people that uses it now, lets keep the props of the component the same

**Comment by nirhart** [comment]
@iaroslavshvets

**Comment by iaroslavshvets** [comment]
But we are missing 3rd state in this case. Boolean doesn't cover it. That's why I've to change it to string and give different name. Or as a compromise I can leave old prop as well,  but Mark it deprecated.

**Comment by nirhart** [comment]
@iaroslavshvets Its not a real error, its just a bad storybook, please see this - https://github.com/wix/wix-style-react/pull/779

**Pull request closed without merging**
