### PR TITLE
Add 'small' vertical row padding support to table/data table

### PR DESCRIPTION
**Pull request by borislit**
### 🔦 Summary
This PR adds a new "small" option to rowVerticalPadding property of the Table
...

### ✅ Checklist

- [ V] 👨‍💻 API change is approved by the UI Infra Developers 
- [ V] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [V ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
<Table>
  - [ ] Visual test

Approved by : Justina Ramanauskaitė @Domas Markevičius

### CODE REVIEW

**Comment by TalZa1810** [comment]
Hi @borislit , thanks for the contribution. 
Can you please [sign your commits](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits) so that CI will run?

**Comment by borislit** [comment]
@TalZa1810 done

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6399

**Review by TalZa1810 — APPROVED** [review]
Hi @milkyfruit @justinara ,
Can you please approve the change? Adding `12px` for padding top and bottom of table item (`rowVerticalPadding` prop).
Also, I saw that the Zeplin file is not updated with the new name so it needs to be updated (a Jira task should be opened for this). In the zeplin file it seems like we have `tiny`, `small` (default) and `medium` in comparison of the current implementation which has `small`, `medium` and `large`:
https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5ecbcbf65a4b1549bb0923df  
https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5cb9dbccfe244b013fdc3c38

@borislit - I saw that the eslint has added some unnecessary brackets. Can this be removed please?

Other than that, seems fine.

**Review by justinara — APPROVED** [review]

**Review by milkyfruit — APPROVED** [review]

**Comment by TalZa1810** [comment]
We've decided to stick with size `small` instead of `tiny` in order for the Table row size to be aligned with the `TableListItem` size. We are not 100% sure that we will add the `tiny` size in the feature, therefore we didn't want to add size `tiny` without size `small`. 
This is why currently the zeplin specs are not aligned with the current implementation. It is still under UX research.

**Pull request merged**
