### PR TITLE
<Timeline/> - add gap prop

### PR DESCRIPTION
**Pull request by mjurfest**
### 🔦 Summary

- Add marginBottom prop to <Timeline/> to allow the user to customize distance between items

### ✅ Checklist

- [X] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit 
- 📚 Change is documented
  - [X] API description
- 🔬 Change is tested
  - [X] Visual test

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6739

**Comment by milkyfruit** [comment]
@mjurfest Is there a benefit to let customize each item's margin separately? I think it could be joined under a single prop `gap`. What do you think?

**Comment by mjurfest** [comment]
@milkyfruit I agree, i will change it

**Comment by milkyfruit** [comment]
@mjurfest Hey, I guess something's wrong with the build, I can't see the change of this commit: 
https://github.com/wix/wix-style-react/pull/6739/commits/07c6e3e31ae78ad123f20911cd6d7010288a5c8a

**Comment by mjurfest** [comment]
@milkyfruit I fixed the issue, it should be ok after the tests run

**Review by milkyfruit — APPROVED** [review]
@mjurfest @TalZa1810 the feature looks great, I approve it.

**Review by TalZa1810 — APPROVED** [review]
looks good. 
fails on visuals which are not related.

**Pull request merged**
