### PR TITLE
<PopoverMenu/> - change popover padding to 12px instead of 10px

### PR DESCRIPTION
**Pull request by roibWix**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by roibWix** [comment]
https://jira.wixpress.com/browse/DSM-872

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6860/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6860

**Comment by roibWix** [comment]
Hey @EgoziE ,
I think all the visual tests are ok according to the padding changes.
Can I get your opinion? 
https://jira.wixpress.com/browse/DSM-872
https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5c90f6ad5947a201e2386885

**Review by justinara — APPROVED** [review]

**Pull request merged**
