### PR TITLE
<CounterBadge />- Change style for newDashboard theme

### PR DESCRIPTION
**Pull request by dht**
### 🔦 Summary

newDashboard theme, changing the <CounterBadge /> general backgroundColor

### CODE REVIEW

**Comment by dht** [comment]
Pls note: passing this depends on fixing the missing css rule:
https://wix.slack.com/archives/C39FTGUBZ/p1612676095308900

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6710

**Review by EgoziE — APPROVED** [review]

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6710/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6710

**Pull request merged**
