### PR TITLE
BusinessDashboard Theme: Fix FontUpgrade not matching theme active state

### PR DESCRIPTION
**Pull request by ronenst**
### 🔦 Summary

Wrapping in `<ThemeProvider/>` with `active: false` still causes the `FontUpgrade` to apply.

Maybe a safer fix would be?
```ts
   componentWrapper: ({ children }) => active ? <FontUpgrade>{children}</FontUpgrade> : <>{children}</>, 
```

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6206

**Comment by adicicurel** [comment]
@ronenst There was a specific request to always apply FontUpgrade on BusinessDashboard theme by UX, 
Initially i did what you are writing in this PR.

**Review by shlomitc — APPROVED** [review]
LGTM

**Comment by ronenst** [comment]
@adicicurel To clarify, having FontUpgrade active even if the theme is not set to active is intentional?

**Comment by ronenst** [comment]
I can only add the `ThemeProvider` when the FT is enabled, but the current behaviour is very surprising. Once expects that setting `active` to `false` will mean no changes are made to the existing styling even if it's a new wrapper.

**Comment by shlomitc** [comment]
I agree - this is a necessary change

**Comment by adicicurel** [comment]
But now you need to pass two active states, one for the font upgrade and one for our theme, since those are two different specs.
Or remove the fontUpgrade from the theme and wrap it when you wrap with ThemeProvider

**Comment by adicicurel** [comment]
According to UX (Ayelet Livne), when we launch, font upgrade would be a must for the dashboard, therefor we need it even if turning the theme off.

**Comment by shlomitc** [comment]
@adicicurel - I think that these are two unrelated features.

**Pull request merged**
