### PR TITLE
`<Slider/>`- expanding clickable area and aligning Slider to spec constrains (#4997)

### PR DESCRIPTION
**Pull request by TalZa1810**
### 🔦 Summary

1. Expanding clickable area 
2. Improving css- disable colors and aligning Slider to the constrains described in the spec.

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [x] Visual test

### CODE REVIEW

**Comment by TalZa1810** [comment]
Hey @ZilvinasMaciulis ,
I've expanded the clickable area of both the slider and the slider handle as we've discussed:
https://wix-wix-style-react-pr-4997.surge.sh/?path=/story/components-api-components--slider

Please let me know if we can merge. Also, if you want me to update the disable colors, please let me know when the zeplin spec is updated.

Thanks :)

**Comment by ZilvinasMaciulis** [comment]
@TalZa1810 

Cool. Hover behavior is just what was expected. Although there is a sort of mouse cursor flicker. When you move the mouse vertically across the component in the mid, right over the slider bar, the cursor changes from pinter to default then again to a pointer. Rapidly moving the cursor causes a flicker between its states.

The cursor should remain a pointer on all hover area parts of the component 

Disabled Colors - working on it at the moment. Will update specs shortly

**Comment by TalZa1810** [comment]
Hi @ZilvinasMaciulis ,
Since the animation doesn't work as expected when there are multiple handles, I've disabled the animation and will implement this in a different PR dedicated for this feature.
Meanwhile, this PR includes the improvements of the constrains (margins, paddings...) & expanding the clickable area (for both knob and slider). 
Moreover, I've improved some of the examples (the StartPoint & custom marks examples).
Since you've already reviewed this, I'm merging this.

**Comment by TalZa1810** [comment]
fails on visuals which are not related to the change.

**Pull request merged**
