### PR TITLE
< WixStyleReactProvider/> — Improved story

### PR DESCRIPTION
**Pull request by milkyfruit**
Added the full list of changes as the examples.
@justinara please take a look at these components:
- Table
- Accordion

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6982/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6982

**Comment by milkyfruit** [comment]
@mykas could you merge this PR?

**Comment by TalZa1810** [comment]
This story is still listed under "WIP". Maybe we should move it to "Components" section.

**Pull request merged**
