### PR TITLE
<Input />(Input.js) - removed size prop

### PR DESCRIPTION
**Pull request by Faradey27**
### What changed

- remove unused prop

### Why it changed

- because prop was unused

---

- [x] Change is tested
- [x] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by ChenRoth** [comment]
it's actually been used for InputWithTags, don't remove it

**Comment by Faradey27** [comment]
@ChenRoth but InputWithTags do not accept size prop and inside of Input size prop is not used

**Comment by ChenRoth** [comment]
it can be used, and i'm actually using it in another PR to fix a `<MultiSelect>` bug

**Comment by Faradey27** [comment]
@ChenRoth it used inside of ThemedInput.js and I removed it from Input.js, so i do not see a problem)

**Comment by Faradey27** [comment]
@ChenRoth it was just removed from propTypes and defaultProps inside Input.js, where it not used

**Comment by ChenRoth** [comment]
oh, I thought you were talking about ThemedInput.js, as `<Input>` refers to it inside other components
ok

**Pull request closed without merging**
