### PR TITLE
`<Dropdown/>`- adding an example of clear button

### PR DESCRIPTION
**Pull request by TalZa1810**
### 🔦 Summary
Adding an example of clear button

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by shlomitc** [comment]
I don’t think it makes sense for a Dropdown to have a clear button. Clear is related to typing usually and not for selection. Is this in the specs? Ux approves?

**Comment by mosheKerbel** [comment]
> I don’t think it makes sense for a Dropdown to have a clear button. Clear is related to typing usually and not for selection. Is this in the specs? Ux approves?

If this is the case, then this is really a high priority issue that we need to solve.
Users get props like this `clearButton` in the API due to inheritance, so we need not to include them in auto-docs.

**Comment by TalZa1810** [comment]
I asked the user for his `spec` to see if this was part of his design. I wait for his reply.

**Comment by shlomitc** [comment]
image
@milkyfruit - does this make sense for our `<Dropdown/>` component? I understand it when we're in "Autocomplete" mode, but don't think it should be for the "select" mode

**Comment by TalZa1810** [comment]
The user said that he just played with the component. It's not something he got from the designer.

**Comment by shlomitc** [comment]
Then let’s close this PR and suggest alternatives if needed

**Comment by milkyfruit** [comment]
there was a similar github issue a while ago for time or date picker...
Nor then, nor now any designer requested for it.
Let's close this issue until we have a real use case.

**Pull request closed without merging**
