### PR TITLE
disabled dropdown base broder color is being overrided

### PR DESCRIPTION
**Pull request by urig-wix**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6920/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6920

**Review by jonathanadler — COMMENTED** [review]
Looks good, thanks!

However I think we just need to add the `!important` to the `color` rule (above the border-color)

Thanks!

**Comment by urig-wix** [comment]
> Looks good, thanks!
> 
> However I think we just need to add the `!important` to the `color` rule (above the border-color)
> 
> Thanks!

added !important to lines 263, 268 instead of the current ones (264, 269) and it stopped working. maybe i didnt get your comment right?

**Comment by jonathanadler** [comment]
> > Looks good, thanks!
> > However I think we just need to add the `!important` to the `color` rule (above the border-color)
> > Thanks!
> 
> added !important to lines 263, 268 instead of the current ones (264, 269) and it stopped working. maybe i didnt get your comment right?

No no, you're good, I wrote my comment very badly 🤦‍♂️ 

What I meant is that we should probably also add an `!important` to the `color` rule (in addition to this one), so that the text color of the disabled dropdown will also work.

Sorry for the mixup

**Comment by jonathanadler** [comment]
@alexgoncharwix 
Do you want to add the native dropdown issue fix here?

**Comment by jonathanadler** [comment]
So @alexgoncharwix I think we can merge this PR, and you can add your fixes in another branch.
Is that ok?

**Review by jonathanadler — APPROVED** [review]

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6920/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6920

**Pull request merged**
