### PR TITLE
Add new Info3 icon

### PR DESCRIPTION
**Pull request by alexgoncharwix**
This icon exists in Design System but is missing in wix-style-react.
Now we need in it in media-platform-client.
https://www.dropbox.com/sh/sydugmjm8a08jkq/AACZzqWLLrhvP8nCAmARbs0ja?dl=0

## Before you request a review, please make sure to check the following boxes:

- [x] Explain what has changed.
- [x] Explain why the change is needed.
- [ ] Added tests.
- [ ] Update documentation.
- [ ] Merge master with no conflicts.
- [ ] Make sure the build is passing on ci.
- [ ] If this pr closes any issue, please add a github link to close it.
- [ ] If you changed something in the product design/UX, you got the approval of [Ben Benhorin](https://wix.slack.com/messages/@benb).

### CODE REVIEW

**Comment by lbelinsk** [comment]
@milkyfruit is it ok to add it in addition to what we have today?
image

**Comment by alexgoncharwix** [comment]
They are two different icons 

1) One in a circle is for tooltips 
http://joxi.ru/ZrJJBdRc1Z5p8r

2) And 2nd is an icon for circle buttons http://joxi.ru/LmGJg5KcRdN6Xr
we don't want a circle inside other circle

**Comment by milkyfruit** [comment]
@lbelinsk @alexgoncharwix We already have Info icon in Wix-Style, which is "**Info2**". No need for additional info icons.

**Comment by lbelinsk** [comment]
@alexgoncharwix please upload the updated icon, then we will merge it.
sorry for the trouble...

**Comment by alexgoncharwix** [comment]
@lbelinsk updated, plz merge if everything is ok

**Pull request merged**
