### PR TITLE
<TimeInput/> - add status indication

### PR DESCRIPTION
**Pull request by ArturasCH**
### 🔦 Summary

Need to have an error state in TimeInput just like in wix-ui-backoffice

### ✅ Checklist

- ✅ 👨‍🎨 UX change is approved by the Design System UX @milkyfruit
- 📚 Change is documented
  - ✅ API description
- 🔬 Change is tested
  - ✅ Component
  - ✅ Visual test

### CODE REVIEW

**Comment by EgoziE** [comment]
Hi @ArturasCH 
Did you discuss this change with someone from our team?

**Comment by ArturasCH** [comment]
> Hi @ArturasCH
> Did you discuss this change with someone from our team?

Yesterday spoke with Mykolas about it (our use case)

**Comment by EgoziE** [comment]
We have a dedicated slack channel in order for conversations like this one to be public to all team members.
**Before** develpment we discuss `design` and `API`.
Please take the time to read our [contribution guide](https://github.com/wix/wix-style-react/blob/master/CONTRIBUTING.md) there you'll find explanations how to sign your commits and other important guidelines.

Can you please share your design before we discuss the API?

**Comment by ArturasCH** [comment]
Moving to slack to discuss design/API related things

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5800/

**Comment by milkyfruit** [comment]
@ArturasCH the change from design side looks great, there's just one small detail missing — `statusMessage` prop.

**Pull request merged**
