### PR TITLE
Madefor - added two Q&A

### PR DESCRIPTION
**Pull request by EgoziE**

### CODE REVIEW

**Comment by EgoziE** [comment]
image

**Comment by EgoziE** [comment]
image

**Comment by shlomitc** [comment]
What is Madefor regular? weight="normal"?
We shouldn't really care if it's Helvetica 55, we care for the appropriate prop name and value
I think we should also map it to the correct Text/Heading prop

**Comment by ayeletr** [comment]
Yes, ok we can use the SB text name/prop.  
I created these examples for UX issues, that can happen after the change, following your request to have "common UX pitfalls". 
I suggest we'll have another section (title) under Q&A, named "Common UX Pitfalls",
And put the UX example there. 
What do you think? Tell me if you have other idea

**Comment by shlomitc** [comment]
@ayeletr - sounds good, let's add a subsection for UX related issues

**Pull request merged**
