### PR TITLE
Removing unnecessary direct lodash dep

### PR DESCRIPTION
**Pull request by aryelu**

### CODE REVIEW

**Comment by sdoomz** [comment]
I found that plain `lodash` package doesn't exist in `dependencies` at all. 
What do you think about adding `lodash.omitBy` to dependencies and importing methods as in other places?

```
import includes from 'lodash.find';
import omitBy from 'lodash.omitBy';
import isUndefined from 'lodash.isundefined';
```

**Comment by aryelu** [comment]
@sdoomz updated

**Comment by nirhart** [comment]
This is the worst way to import it https://medium.com/@ericchan/best-smallest-way-to-import-install-lodash-6622802dbeb, we should actually just use lodash-es and then we can import like this:
import {includes, omitBy, isUndefined} from 'lodash-es'

**Comment by aryelu** [comment]
jest needed some config http://stackoverflow.com/a/42353679

**Comment by aryelu** [comment]
We need to also transpiling of `node_modules/lodash-es` directory, yoshi ignores it all

**Comment by roymiloh** [comment]
@aryelu [externalUnprocessedModules](https://github.com/wix/yoshi#yoshiexternalunprocessedmodules) should work for you (both in consumer project and wix-style-react itself, where we run redundant webpack step, but still), but generally we might need to find a better solution.

**Comment by nirhart** [comment]
We will do something more general regarding moving to lodash-es

**Pull request closed without merging**
