### PR TITLE
cheatsheet- adding new components 

### PR DESCRIPTION
**Pull request by TalZa1810**
### 🔦 Summary
Adding the new components to the cheatsheet (Content Widgets Family) : 
- Sparkline Chart
- Selectable Accordion
- StackedBarChart

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6068

**Comment by TalZa1810** [comment]
@ayeletr 
I've added the new components (`SparklineChart`, `SelectableAccordion`, `StackedBarChart`) to the cheatsheet. The numbering of `Stacked Bar Chart` and `Selectable Accordion` are  missing.

**Comment by TalZa1810** [comment]
Hi @milkyfruit ,
There's no spec for `Stacked Bar Chart` so I'm not sure which number is it. 
As for the `Selectable Accordion`- it was developed and merged. There's no number for this as well. Can you please update me so I can merge this to the Cheatsheet?

Thanks.

**Comment by TalZa1810** [comment]
cheatsheet doesn't have visuals and e2e tests.

**Pull request merged**
