### PR TITLE
<DropdownLayout/> - fix scroll behaviour

### PR DESCRIPTION
**Pull request by yardnsm**
Fix for https://github.com/wix/wix-style-react/issues/2169.

Please take a look at the changes. I'm using `getBoundingClientRect()` to retrieve an element's height, maybe there is a more efficient way to do this?

### CODE REVIEW

**Comment by hepiyellow** [comment]
@wuwa @LittleTal @milkyfruit 
Is this the required UX behaviour? (That the selected option will always be in the center)
It seems that the solution in say, native `<select/>` with chrome, or MaterialUI <Select/>,
is that when a selected option is not fully visible, then the scroll is applied the **"minimum adjustment needed"** in order to make it fully visible.

Whats your decision?

**Comment by yardnsm** [comment]
Also, in the native `<select/>`, when the focus is on the last item and the user presses `ArrowDown`, the focus does not go the first element (in wsr it *does*). Same thing goes when pressing `ArrowUp` when the first item is in focus.

**Comment by hepiyellow** [comment]
## Using focus
just one concern. It means that the options are focusable (have `tabIndex`).AM I right?
So need to make sure that TAB does NOT focus on them, but rather got OUT of the DropdownLayout.

## Cyclic navigation
This is a UX decision.
There are a few decisions to make:

### Optional
Can the consumer disable ALL cyclic behaviour?

### Repeated-Key
When cyclic navigation is enabled, it is still important to disable it when repeated-key is pressed.
Meaning that if you press down arrow and keep it pressed, so you navigate FAST through the options, in which case you don't want to have cyclic navigation. It is very annoying.

### Scroll dependent
Another logic may say that if the options container has scroll, then cyclic navigation should be disabled.

@wuwa , @milkyfruit @LittleTal What do you think?

**Comment by yardnsm** [comment]
Regarding to focus: Tab does not focus on the items, as the `onkeydown` event in `<DropdownLayout/>` already prevents it.

**Comment by milkyfruit** [comment]
@hepiyellow @yardnsm 

**Focus / Tab-Index**
The focus should apply to whole container and the selected list item should be switched by using arrow keys. [More about a11y.](https://v9yfnh.axshare.com/#g=1&p=dropdown)

**Cyclic navigation**
I don't have a strong opinion about it. MacOS and Material platforms don't support this feature by default. We can make it as optional property, which could be enabled if needed.

**Scrolling & Repositioning**
When list is longer than a container, on arrow down the list should scroll until the next nearest option, as Erez mentioned:

> It seems that the solution in say, native <select/> with chrome, or MaterialUI , is that when a selected option is not fully visible, then the scroll is applied the "minimum adjustment needed" in order to make it fully visible.

**Comment by hepiyellow** [comment]
ok . So no cyclic behavior yet.

**Comment by hepiyellow** [comment]
# Sorry guys, I think we need to revert this PR !
We can't make each option focusable, since the focus must stay on the input box in cases like AutoComplete.
(so that pressing keyboard letters would type them into the input).

What happens now is that typing letters doesn't do anything.
Furthermore, it is not possible to navigate by keyboard back to the input (I am talking about Autocomplete).

See this [old storybook](https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.1%20%2B%20AutoComplete&full=0&addons=0&stories=1&panelRight=0) where it works properly .

The [new storybook](https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.1%20%2B%20AutoComplete&full=0&addons=0&stories=1&panelRight=0) is broken.

**Pull request merged**
