### PR TITLE
added loading state for stats widget

### PR DESCRIPTION
**Pull request by mariafeldman**
## Before you request a review, please make sure to check the following boxes:

- [ ] Explain what has changed.
- [ ] Explain why the change is needed.
- [ ] Added tests.
- [ ] Update documentation.
- [ ] Merge master with no conflicts.
- [ ] Make sure the build is passing on ci.
- [ ] If this pr closes any issue, please add a github link to close it.
- [ ] If you changed something in the product design/UX, you got the approval of [Ben Benhorin](https://wix.slack.com/messages/@benb).

### CODE REVIEW

**Comment by lbelinsk** [comment]
@mariafeldman is the loader approved by Ben?
I am asking since maybe you can just display a loader without the widget (UX decision)

**Comment by lbelinsk** [comment]
@mariafeldman we are pending for your update about Ben's decision

**Comment by lbelinsk** [comment]
@mariafeldman ?

**Comment by lbelinsk** [comment]
@mariafeldman can I close this?

**Comment by argshook** [comment]
@mariafeldman hello, what's the status?

**Pull request closed without merging**
