### PR TITLE
Fix/dropdown styles

### PR DESCRIPTION
**Pull request by alexgoncharwix**
### 🔦 Summary

Fixes bg color for native mobile more. Refactoring of DropdownNativeSelect to include .overrideStyleParams class and to add these params: MainButtonTextColor, MainButtonTextDisabledColor, MainButtonBorderColor, MainBorderDisabledColor, MainBackgroundColor.

### ✅ Checklist

- [ v] 👨‍💻 API change is approved by the UI Infra Developers 
- [v ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [v ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_6983/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_6983

**Review by jonathanadler — COMMENTED** [review]
First of all, really really great work!
I looked in the storybook and it works very good 👌 

I did notice though that you haven't passed the border-width, and font params to the native select. Was that on purpose?

Also, just one small thing I noticed: The red error border isn't applied to the native select dropdown (see image attached):
image

Again, great work, and thanks!

**Comment by alexgoncharwix** [comment]
> I did notice though that you haven't passed the border-width, and font params to the native select. Was that on purpose?
I checked and it turned out that no border-width, neither font params were supported by native select. In storybook there is a bug and also in WixStores in Product Page there is the same bug.
I'm going to fix it and will add support of border-width and font params.
Thank you for the very good catch :)


> Also, just one small thing I noticed: The red error border isn't applied to the native select dropdown (see image attached):
> image
You are right

**Review by jonathanadler — APPROVED** [review]
Awesome!

Seems like there's only some perfer bundles that need to be bumped, in order for the build to pass.
https://bo.wix.com/performance-stats/reports/606506a72bc9e70133008aad

**Comment by jonathanadler** [comment]
@alexgoncharwix 
Just note that it seems like there's some perfer bundles that need to be bumped, in order for the build to pass.
https://bo.wix.com/performance-stats/reports/606506a72bc9e70133008aad

**Comment by alexgoncharwix** [comment]
@jonathanadler thank you for bumping sizes and merging. I took two day offs and could not do it.
Please let me know when the new version is released. I'll check it in Stores and add some Sleds on our side.

**Pull request merged**
