### PR TITLE
add new theme for button layout

### PR DESCRIPTION
**Pull request by ArtemAstakhovWix**
Our designer (Kyrylo Levashov) added new theme for buttons
default state: https://www.screencast.com/t/8uwFl8g9jAs
hover and active state: https://www.screencast.com/t/xcAUpUtCXVh

### CODE REVIEW

**Comment by lbelinsk** [comment]
Can merge if it is approved by Kosover

**Comment by nir-k** [comment]
Hi,
Sorry, Artem there's no need to add new style you can just use the regular 5.3a button.

screen shot 2017-08-03 at 11 01 54

I will talk to Kyryl and Dado to make sure we are all aligned.

Thx.

**Comment by lbelinsk** [comment]
@nir-k Can you please decide what should we do with this pr?
Please see the relevant email

**Comment by lbelinsk** [comment]
Closing it after speaking with Kyrylo Levashov.
He said that they have decided to go with solution from ui lib, that already exists.

**Pull request closed without merging**
