### PR TITLE
update codeowners

### PR DESCRIPTION
**Pull request by jonathanadler**
Using the CODEOWNERS file we can set automatic reviewers for each PR, and restrict the PR's from getting merged without a reviewer's approval.

I've already added @mykas and @argshook to the wix-ui-tpa team, so that they can approve wut code changes when needed.
I currently set the root folder to be owned by Mykolas, Arijus, Egozi, Shlomi and I.
This of course can be changed pretty easily.
We can create another design-systems team for that, or use the infra team for that, doesn't really matter.
But this file will be the basis of ownership for the library.

### CODE REVIEW

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7051/

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7051

**Review by argshook — APPROVED** [review]
i'm all for this, just one thing:

adding codeowners to the root means that every PR will require a review from that list of people?
if that's a yes,then amount of PR review requests might become excessive and thus we'll tend to ignore them. maybe no need to have root codeowners?

**Comment by jonathanadler** [comment]
> i'm all for this, just one thing:
> 
> adding codeowners to the root means that every PR will require a review from that list of people?
> if that's a yes,then amount of PR review requests might become excessive and thus we'll tend to ignore them. maybe no need to have root codeowners?

Hmmm 🤔  good point.

I'll investigate this a bit.

I think we still need codeowners for the root folder, for infra changes and such.

**Comment by jonathanadler** [comment]
I've updated the file according to this: https://wix.slack.com/archives/C056JMHJ5/p1618733697138800?thread_ts=1618733392.138700&cid=C056JMHJ5

**Pull request merged**
