### PR TITLE
Add stats widget example with no border filter

### PR DESCRIPTION
**Pull request by barakplasma**
- [x] Explain what has changed.
Added an example in the storybook of how to create a stat's widget which has a filter which has no border.
screen shot 2018-01-02 at 15 50 57

- [x] Explain why the change is needed.
This example both fixes: #1149 and proves that #1200 is done
- [x] Added tests.
Since this is a demo, no tests included
- [x] Update documentation.
Added the proper title to the new storybook section.
- [x] Merge master with no conflicts.
Ready to go
- [ ] Make sure the build is passing on ci.
- [ ] If this pr closes any issue, please add a github link to close it.
fixes: #1149 
fixes: #1200 
- [ ] If you changed something in the product design/UX, you got the approval of [Ben Benhorin](https://wix.slack.com/messages/@benb).
No changes made

### CODE REVIEW

**Comment by barakplasma** [comment]
I followed @milkyfruit 's suggestion to use dropdown with no border https://github.com/wix/wix-style-react/issues/1149#issuecomment-345954031

**Comment by barakplasma** [comment]
P.S. I realize now that the commit message on https://github.com/wix/wix-style-react/pull/1315/commits/d41c311394361db99d4c7465337b4d79d5f00d23 has a typo and should end in 'grammar'

**Comment by lbelinsk** [comment]
Something I am missing: The user shouldn't pass the `noBorder` prop. It should be already preconfigured in the Stats.Filter component because the user shouldn't be able to render a dropdown

**Comment by lbelinsk** [comment]
@barakplasma the correct implementation will be to use ButtonWithOptions in favor of Dropdown. There is a new theme for the Button  'no-border'.

**Comment by barakplasma** [comment]
opening a new PR

**Pull request closed without merging**
