### PR TITLE
Add Sort icons

### PR DESCRIPTION
**Pull request by malcolmmadsheep**
Add several sorting order icons

### CODE REVIEW

**Comment by lbelinsk** [comment]
Thanks @malcolmmadsheep
Can you please add screenshots of the icons?
They must be approved by @milkyfruit

**Comment by malcolmmadsheep** [comment]
New icons for Media Manager G6

sortaz
sortlastmodifiedasc
sortlastmodifieddesc
sortza

**Comment by milkyfruit** [comment]
Looking at pngs icons look good, please send me svgs as well, so I can optimise them and make sure it fits this upcoming format: https://github.com/wix/wix-style-react/issues/961

**Comment by milkyfruit** [comment]
Updated the icons together with @malcolmmadsheep. From my side I approve this PR @lbelinsk @argshook

**Comment by milkyfruit** [comment]
The updated icons with 24x24px canvas size are [here](https://drive.google.com/drive/folders/0B3MbBTg6SmtrMjNMX0E2aVA3TGM)

**Comment by malcolmmadsheep** [comment]
screen shot 2017-11-21 at 4 51 11 pm

**Pull request merged**
