### PR TITLE
add text props in floating notification component

### PR DESCRIPTION
**Pull request by zivl**
It is very difficult to control the text within the `FloatingNotification` component. 
I believe, for a start, those simple props can be used to make some small convenient changes as part of the `Text` component's props

### CODE REVIEW

**Comment by shlomitc** [comment]
why is this needed? what are your product requirements?

**Comment by zivl** [comment]
@shlomitc need to have this kind of notification: https://app.zeplin.io/project/5acb89b4c9e513459f2e90a6/screen/5c9a723179d02b35ea496d91

**Comment by shlomitc** [comment]
You should use the SectionHelper component instead and put your content as children
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=SectionHelper&full=0&addons=0&stories=0&panelRight=0

**Comment by zivl** [comment]
oh... this is much better!
ok, your call if you'd like to close this PR :)

**Comment by shlomitc** [comment]
Great, thanks for the PR anyway

**Pull request closed without merging**
