### PR TITLE
add working-with-monorepo.md doc

### PR DESCRIPTION
**Pull request by argshook**
This PR adds a document with tips and conventions on how to work with monorepo

@EgoziE @mykas @jonathanadler please take a look and add anything i missed.

For example, i'm not entirely sure what should be the commit convention for wix-ui-tpa

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6664

**Review by shlomitc — APPROVED** [review]

**Comment by jonathanadler** [comment]
I wonder if we want to add this part as well (for wix-ui-tpa):
https://github.com/wix/wix-ui-tpa/blob/master/docs/internal/VERSION_RELEASE.md#changelog
image

**Comment by argshook** [comment]
@jonathanadler i wouldn't be against adding it, just maybe some confusion that library is react but convention is angular? but that's negligible so `¯\_(ツ)_/¯ `

**Comment by jonathanadler** [comment]
> @jonathanadler i wouldn't be against adding it, just maybe some confusion that library is react but convention is angular? but that's negligible so `¯\_(ツ)_/¯ `

It's just the Angular preset, because they use it in their project 😄

**Comment by argshook** [comment]
> > @jonathanadler i wouldn't be against adding it, just maybe some confusion that library is react but convention is angular? but that's negligible so `¯\_(ツ)_/¯ `
> 
> It's just the Angular preset, because they use it in their project

oh yea i'm aware, just thought maybe namings can raise questions. but again, this is a no-topic, this banner is just a merge away, i don't think anyone would be against

**Review by jonathanadler — APPROVED** [review]
In any case, it's looking good 👌

**Comment by argshook** [comment]
merging, if there are any updates let's do it in separate PR

**Pull request merged**
