### PR TITLE
<SelectorList> - change padding when there is no search bar

### PR DESCRIPTION
**Pull request by seifange**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by roibWix** [comment]
Hey @seifange ,
The ci build is failing because the commit is not signed.
Please follow this [document](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits) in order to sign the commit.
If you have any issue, let us know and we'll try to help.

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6434

**Comment by roibWix** [comment]
Hey, I checked it out.
In your suggested solution, the visual tests with the search bar are failing and they shouldn't.
Please add a visual test for a case without the search bar.

**Comment by seifange** [comment]
@roibWix fixed the tests and the build is green 😄

**Comment by roibWix** [comment]
@seifange, Great!!

**Review by roibWix — APPROVED** [review]

**Comment by sidoruk-sv** [comment]
@seifange could we revert this change?
Cause for our project this causing loosing of inner paddings before subHeader, and it looks a bit cranked:
Screenshot 2020-12-30 at 16 59 46Screenshot 2020-12-30 at 16 59 39

Failed eyes tests related to this change:
https://wixeyes.applitools.com/app/test-results/00000251792961756884/?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110

**Comment by sidoruk-sv** [comment]
✅ Discussed in DMs with @seifange and @EgoziE

**Pull request merged**
