### PR TITLE
<CheckToggle/> - add animate prop

### PR DESCRIPTION
**Pull request by mjurfest**
### 🔦 Summary

- Add `animate` prop to `<CheckToggle/>`. It animates using `<PulseAnimation/>`

### ✅ Checklist

- [X] 👨‍💻 API change is approved by the UI Infra Developers @TalZa1810 
- 📚 Change is documented
  - [X] Story
  - [X] API description

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6733

**Review by ZilvinasMaciulis — APPROVED** [review]

**Review by TalZa1810 — APPROVED** [review]

**Comment by EgoziE** [comment]
Hey @mjurfest and @TalZa1810 
I'm sorry to be the party pooper, but we'll have to re-think this.
CheckToggle is an atom component, it doesn't make sense to make it composed with PulseAnimation internally.
I'm reverting this PR, let's talk on Monday.

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6733/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6733

**Pull request merged**
