### PR TITLE
 <Icons /> - migration EditableSelector, DatePickerDropdown

### PR DESCRIPTION
**Pull request by Faradey27**
### What changed

    - migrated EditableSelector
    - migrated EditableRow
    - migrated DatePickerDropdown

### Why it changed

migration to new icons

---

- [x] Change is tested
- [x] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by Faradey27** [comment]
@milkyfruit can you approve EditableSelector and DatePickerDropdown components?

**Comment by shlomitc** [comment]
@milkyfruit - can you please open an issue regarding the button size?

**Comment by milkyfruit** [comment]
@shlomitc added the issue: https://github.com/wix/wix-style-react/issues/1937

**Comment by shlomitc** [comment]
@milkyfruit - thanks!

**Pull request merged**
