### PR TITLE
Added favorite icons

### PR DESCRIPTION
**Pull request by vladik7244**
Added Favorite and FavoriteFilled icons

They are necessary for MediaManagerG6 project

### CODE REVIEW

**Comment by shlomitc** [comment]
@milkyfruit? - do you approve adding this icon

**Comment by milkyfruit** [comment]
The icons are slightly different than in Sketch Lib and SVG file contains unnecessary tags / attributes.
Here are the optimised icons:

**favorite.svg**
`<svg xmlns="http://www.w3.org/2000/svg" width="17" height="16" viewBox="0 0 17 16">
  <path d="M8.5,0 L5.729,5.069 L0,6.112 L4.015,10.287 L3.248,15.999 L8.5,13.512 L13.753,16 L12.986,10.287 L17.001,6.112 L11.272,5.069 L8.5,0 Z M5.087,9.942 L2.032,6.764 L6.391,5.971 L8.5,2.114 L10.61,5.971 L14.969,6.764 L11.914,9.942 L12.498,14.289 L8.5,12.397 L4.502,14.29 L5.087,9.942 Z"/>
</svg>
`

**favorite-active.svg**
`<svg xmlns="http://www.w3.org/2000/svg" width="17" height="16" viewBox="0 0 17 16">
  <polygon points="8.5 0 5.729 5.069 0 6.112 4.015 10.287 3.248 15.999 8.5 13.512 13.753 16 12.986 10.287 17.001 6.112 11.272 5.069"/>
</svg>`

**Comment by vladik7244** [comment]
@milkyfruit I've update icons

**Comment by milkyfruit** [comment]
@vladik7244 Thanks, looks good now.

**Comment by vladik7244** [comment]
@shlomitc So let's merge?

**Pull request merged**
