### PR TITLE
<FontUpgrade/> - Fix Modal, Popover, Tooltip content

### PR DESCRIPTION
**Pull request by EgoziE**

### CODE REVIEW

**Comment by shlomitc** [comment]
How does it fix it?

**Comment by EgoziE** [comment]
> How does it fix it?

when it's undefined the default is true

**Comment by EgoziE** [comment]
I checked it on a clean yoshi project.
Managed to reproduce and test the fix.

**Comment by shlomitc** [comment]
So maybe the default should be false?

**Comment by EgoziE** [comment]
Yeah it should have, when I added this prop it was only was only for the Storybook add-on..
Changing it now means it will be breaking.

**Comment by EgoziE** [comment]
I can delete this prop and replace it with a disabled instead

**Pull request merged**
