### PR TITLE
Wrong button display property for MessageBox HeaderLayout #580

### PR DESCRIPTION
**Pull request by Faradey27**
Resolved https://github.com/wix/wix-style-react/issues/580

Manually tested in: Chrome, Safari, FF, not directly in IE11(by devtools in some of the projects that uses wix-style-react)

### CODE REVIEW

**Comment by nirhart** [comment]
What was the problem?

**Comment by Faradey27** [comment]
@nirhart i tried to explain this in issue,
but in general, if i m using normalize.css or one of my client, then button content will be not centered, so "cross" icon will be at the right part of button, instead of the center

**Comment by Faradey27** [comment]
and thats the reason https://stackoverflow.com/questions/35464067/flexbox-not-working-on-button-element-in-some-browsers,

because button could not be display: flex, it not according to standart

@nirhart 

tommorow i can attach screnshots

**Comment by nirhart** [comment]
No need for screenshot :), I'll recheck it tomorrow with IE and Edge and will merge if everything works good

**Comment by Faradey27** [comment]
@nirhart sounds good, thank you

**Pull request merged**
