### PR TITLE
Docs/testkit doc cleanup

### PR DESCRIPTION
**Pull request by argshook**
removed README.TESTKIT.md and moved testkit comments to driver implementations for following components:

* Breadcrumbs
* Loader
* Page
* EmptyState
* AddItem
* RichTextArea

react-autodocs-utils parses testkits and shows comments from source, so no need for manual markdown files

### CODE REVIEW

**Comment by hepiyellow** [comment]
Where does it take the Code example?
Does it generate it with a template?

**Comment by hepiyellow** [comment]
The generated testkit docs, don't have function arguments and return value type.
So we are loosing info here !

[Current Breadcrumbs testkit ](https://wix-wix-style-react.surge.sh/?selectedKind=6.%20Navigation&selectedStory=6.2%20Breadcrumbs&full=0&addons=0&stories=1&panelRight=0)

[Generated Breadcrumbs testkit](https://wix-wix-style-react-pr-2589.surge.sh/?selectedKind=6.%20Navigation&selectedStory=6.2%20Breadcrumbs&full=0&addons=0&stories=1&panelRight=0)

**Comment by argshook** [comment]
code examples are here https://github.com/wix/wix-ui/tree/master/packages/wix-storybook-utils/src/AutoTestkit/examples

generated  docs do have function arguments.

you are right that they don't have return types (which is mostly impossible to parse in js) but i don't see it as a huge negative

**Comment by argshook** [comment]
@hepiyellow 

>Does autodocs support jsdoc @param and @returns tags?

currently no,  but you're welcome to submit a PR for that if you wish in here https://github.com/wix/react-autodocs-utils

**Pull request merged**
