### PR TITLE
<StatisticsWidget/> - added alignItems prop

### PR DESCRIPTION
**Pull request by yogevitz**
### 🔦 Summary

added alignItems property

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [x] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
  - [x] API description
- 🔬 Change is tested
  - [x] Component

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5931/

**Comment by shlomitc** [comment]
@yogevitz - thanks for the hard work.
This PR fails due to visual tests. Seems like the ellipsis behavior is broken once the flex is applied

Before: 
image
After:
image

This affects all labels (also in the description)

@milkyfruit - just making sure that the content alignment is approved from your side

**Comment by milkyfruit** [comment]
Yes, this feature was instructed by me. Ellipsis should remain though.

**Comment by yogevitz** [comment]
@shlomitc @milkyfruit I fixed the ellipsis issue

**Pull request merged**
