### PR TITLE
[wix-style-react] - <Modal /> introduced screen prop for spacing between viewport and modal content

### PR DESCRIPTION
**Pull request by egidijusja**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by EgoziE** [comment]
Modal is just a mechanism component, no styles should be applied to it.
By adding this padding prop (specially with that 48px default) you're going to break every modal our consumers have.

Are you sure this is correct place for this fix?

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6556

**Comment by egidijusja** [comment]
> Modal is just a mechanism component, no styles should be applied to it.
> By adding this padding prop (specially with that 48px default) you're going to break every modal our consumers have.
> 
> Are you sure this is correct place for this fix?

Actually this should be draft PR, sorry for that. Actually we had a meeting with Domas and @mykas regarding this one. Modal design guidelines tell that modal should have margins of 48px. This behaviour right now is implemented in some modals (children) already:
https://github.com/wix/wix-style-react/blob/master/src/BaseModalLayout/BaseModalLayout.st.css#L60
https://github.com/wix/wix-style-react/blob/master/src/CustomModalLayout/CustomModalLayout.st.css#L24

Although, there is a problem with this approach, e.g. CustomModalLayout accepts props like width, height, maxHeight and if some of these props are provided margins calculation logic is overridden and modal doesn't follow design guidelines anymore. So the idea was to introduce padding prop for Modal component with default value `0px` and once we move library to new major version change default value to `48px` and fix other modal components styles which try to calculate margins themselves.

**Review by mykas — APPROVED** [review]
Looks very clean and good!

**Pull request merged**
