### PR TITLE
<Icons /> - migrate ColorPicker, FieldLabelAttributes

### PR DESCRIPTION
**Pull request by Faradey27**
### What changed

...

### Why it changed

...

---

- [ ] Change is tested
- [ ] Change is documented
- [ ] Build is green
- [ ] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by Faradey27** [comment]
@milkyfruit https://wix-wix-style-react-pr-1945.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.3%20Field%20With%20Selection&full=0&addons=0&stories=1&panelRight=0 put some info inside of `info` input and `info icon` will appear near to input

**Comment by milkyfruit** [comment]
@shlomitc @argshook Does `<FieldWithSelection>` going to use `<FormField>` wrapper after 4.7.0 update?

**Comment by shlomitc** [comment]
Hey @milkyfruit.
The short answer is no.

The long answer:
The new `FormField` component will eventually replace all different kind of composition components that were created (`TextField`, `TextArea`, etc..). It works as a wrapper to components without applying styles to it's children.
It will not work out of the box for the `FieldWithSelection` because this composition applies styles to the base components like Checkbox and Input. So actually its required to create a new component like `InputWithSelection` that will compose all the styles and then just wrap it with `TextField`

**Comment by Faradey27** [comment]
@milkyfruit updated

**Pull request merged**
