### PR TITLE
Added play next and play previous icons

### PR DESCRIPTION
**Pull request by vladik7244**

### CODE REVIEW

**Comment by argshook** [comment]
please sync with @milkyfruit regarding the design of icons. There's an effort to unify/betterify all icons in #961 and so new icons should probably adhere to that. anyway, @milkyfruit knows best

**Comment by argshook** [comment]
@vladik7244 hey, did you have a chance to get in touch with @milkyfruit? He's the man to talk to  regarding icons

**Comment by vladik7244** [comment]
@argshook Yes, but these icons is not needed anymore. Design has been changed

**Comment by vladik7244** [comment]
@argshook I think this PR can be closed

**Comment by argshook** [comment]
@VladaLeykin great, thanks for the headsup! closing

**Pull request closed without merging**
