### PR TITLE
Add link theme for ButtonLayout

### PR DESCRIPTION
**Pull request by el-fuego**
LinkLayout can`t be used in my case.
1. For accessibility I need to use <button/> or <a/> for active elements
2. I don`t need for some cases href at all, just a click - need to use button only
3. <LinkLayout><button/></LinkLayout> will have borders and other stuff from button

Here is an example http://joxi.ru/EA4d3B5CDpMe1A.jpg

### CODE REVIEW

**Comment by el-fuego** [comment]
Here is TextLinkLayout
http://joxi.ru/Q2Kga9Mc9vWpR2.jpg

```
            <TextLinkLayout>
              <button onClick={_.noop}>
                button
              </button>
            </TextLinkLayout>

            <TextLinkLayout>
              <a onClick={_.noop} href="#">
                a
              </a>
            </TextLinkLayout>
```

Button with link theme  - is what I need.
It is very common style (see Bootstrap as example), what will be used without any additional hack-wrappers

**Comment by lbelinsk** [comment]
I don't understand what is missing here for you.
You have ButtonLayout and TextLinkLayout which simply wraps their children prop with the relevant  style accordingly.

Do you mean that you don't think that this wrapper model is good? Or is there still something missing for you practically?

**Comment by el-fuego** [comment]
I need <button/> or <a/> inside for accessibility and semantics. How it looks you can see at previous message (looks wrong)

Also, I need two font-sizes (14px and 16px)

**Comment by lbelinsk** [comment]
In my opinion we should improve the current approach and not to add something similar.
I think that instead of this new code it can be integrated inside the current layouts in a way that it will work as expected.

For example, why to use a button inside a textlinkLayout? maybe a ```<div>``` element with onClick will be better, or maybe not.

If you don't think it is the right approach, we can wait for @nirhart for that if it is not urgent..

**Comment by el-fuego** [comment]
In any case, at the future we wil need to use semantic clickable elements.. so I vote for adding theme like it done at Bootstrap (and used by a lot of worldwide users)
How long we need to wait?

**Comment by lbelinsk** [comment]
Nir returns fro a vacation next week. Will it be ok to wait until then?

**Comment by el-fuego** [comment]
Ok, will wait

**Comment by kupriyanenko** [comment]
@harelig, @lbelinsk, @el-fuego I think we should close this PR. As for me, all buttons, event with link style, should have the same layout (paddings, margins, etc). Look in bootstrap: https://getbootstrap.com/docs/3.3/css/#buttons-options

If we will have different layout for different styles of buttons, we will have a mess and button composing will be too complex.

**Comment by kupriyanenko** [comment]
@lbelinsk can we add to `TextLinkLayout` `onClick` handler?

**Comment by kupriyanenko** [comment]
Or, we can leave this PR opened, because it can be used, but change a little bit. We shouldn't change layout for it, we can change only colors.

**Comment by nirhart** [comment]
@kupriyanenko @el-fuego wix-style-react is not bootstrap, its very restricted to wix theming, and wix theming of link looks different from a button, thats why we separated it. I agree that for accessibility we will need some kind of styleless button to be inside TextLinkLayout, but design wise, TextLinkLayout can do exactly what you need.

**Comment by el-fuego** [comment]
About using of current TextLinkLayout or Button:
https://stackoverflow.com/questions/37147842/a-vs-button-vs-div-vs-input-type-button
https://davidwalsh.name/html5-buttons

**Comment by nirhart** [comment]
@el-fuego TextLinkLayout do not restrict you to <a> or to <button>, you can do whatever you want with it.

**Comment by el-fuego** [comment]
See examples at previous messages, where button was wrapped with this component.

Another option is make it as styled button not inside Button, but TextLinkLayout and will support all events

**Comment by lbelinsk** [comment]
@kupriyanenko You shouldn't put ```onClick```  on ButtonLayout, instead put it on it's child component.

Stupid example:

```
<ButtonLayout>
    <div onClick../>
</ButtonLayout>
```

**Comment by el-fuego** [comment]
@lbelinsk https://github.com/wix/wix-style-react/pull/686#issuecomment-320755851 and not div beause of semantics

PR ussless? Ok, will wait 2 hours and close it with realizing all this stuff at my project

**Pull request closed without merging**
