### PR TITLE
❤️ 🎅Updated Readme.md ❤️🎅

### PR DESCRIPTION
**Pull request by mykas**
Here is my 🎅Christmas 🎅edition PR that updates our Readme file and makes it great again.

Here are some points that I wanted to highlight with this readme:
- 👶 Adding badges that tells our users which version is out, which react supports and of course dependencies and devdependencies which we should take care of.
- 🔨  Migration mentioned from v6 to v7 .
-  🕸 Webpack instructions are now gone from the readme and replaced with great link to guidelines.
- ❤️ Emojis everywhere! (yep thats a bullet list point too)
- 🥇 Featuring our testkits as  great feature that nobody in the industry has.
- ⌨️ Typescript support explanation with direct link to our great wsr-stypes library.
- 🎛  More emojis and badges on contribution part.
- Troubleshooting is removed! Not sure why we need this here if users can read it in storybook.

I hope this PR will enable all of you to kick-in some new ideas. 

Ideas that I am not sure about:
- Our teams oval picture as main contributors! Finally we could have our faces shown on the web.
- Gifs with flashing component at the top!

### CODE REVIEW

**Comment by nitayneeman** [comment]
Awesome!

I've planned to do it a long time ago, but never reached that.

The result:
https://github.com/wix/wix-style-react/blob/ef02feb5f5586288503da26b122bb315065696a5/README.md

**Comment by EgoziE** [comment]
Looks awesome!
Someone on the channel complained that our `Requirements` are not "clear enough"
I think it might be better to emphasize it in a `Requirements` too...

**Comment by TalZa1810** [comment]
Looks amazing :)
Maybe when we decide about the issues work process with Jira & Github issues, it's worth mention this here? wdyt?

**Comment by mykas** [comment]
@EgoziE it make sense though I thought that maybe badge is good enough. It just doesnt look good that we have one thing in requirement section and its react version xD beauty over people who are not aware?

**Comment by EgoziE** [comment]
I totally agree with you, maybe under "Setup" it will look nicer.. i dunno

This is a recent discussion about the requirements
https://wix.slack.com/archives/C39FTGUBZ/p1577216673077700

**Comment by mykas** [comment]
@EgoziE  Here you go
Screenshot 2019-12-26 at 12 55 57

**Comment by mykas** [comment]
@TalZa1810 Hmm maybe, but that depends. Do we really want to say to your community that our issues in github resides in jira? Will our jira be open for the web?

**Comment by mykas** [comment]
Anyway, guys! I am gonna merge this and go back to the Christmas table! Food needs to be eaten

**Pull request merged**
