### PR TITLE
wip - test parallel protractor

### PR DESCRIPTION
**Pull request by yanivefraim**
wip

### CODE REVIEW

**Comment by hepiyellow** [comment]
Oh, I just thought about this a week ago,
when I saw Unidriver build running protractor and puppeteer in parallel.

**Comment by yanivefraim** [comment]
> Oh, I just thought about this a week ago,
when I saw Unidriver build running protractor and puppeteer in parallel.

It doesn't work. Eyes tests are failing in parallel mode, I think because of focus issues.
Plan B: split build / tests in CI...

**Comment by hepiyellow** [comment]
@yanivefraim I thought this is about running multiple browsers in parallel...

**Comment by yanivefraim** [comment]
> @yanivefraim I thought this is about running multiple browsers in parallel...

yes, it is...

**Comment by hepiyellow** [comment]
@yanivefraim 
I guess you are in sync with @shlomitc .
He integrated `eyes.storybook` in WSR.
If your effort is trying to reduce build time, then converting tests to use `eyes.storybook` might be a better approach here.

**Comment by hepiyellow** [comment]
@yanivefraim ok. I synced with Shlomi. you don't have to explain.

**Comment by shlomitc** [comment]
done here
https://github.com/wix/wix-style-react/pull/3785

**Pull request closed without merging**
