### PR TITLE
<StatisticsWidget/> - update padding for size tiny

### PR DESCRIPTION
**Pull request by yogevitz**
### 🔦 Summary

updated `padding` on sides of each item in the `<StatisticsWidget/>`
changed from `30px` to `24px`

### ✅ Checklist

- [x] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6472

**Comment by TalZa1810** [comment]
Hi @milkyfruit ,
Is this part of[ this effort](https://jira.wixpress.com/browse/DSM-1333)? Can you please clarify?

**Comment by milkyfruit** [comment]
@TalZa1810 nope, it's just aligning with the current specs.
- **Current specs: https://zpl.io/a3MgDYd**
- Reduced spacing effort specs (irrelevant for this PR): https://zpl.io/a87vGwJ

@yogevitz side paddings should remain 30px, only the inner paddings should change:
image

**Comment by yogevitz** [comment]
@milkyfruit, now added 6px padding to the sides (in addition to the inner 24px)

**Review by milkyfruit — APPROVED** [review]
@yogevitz @TalZa1810 looks great! I think we can merge it.

**Review by TalZa1810 — APPROVED** [review]

**Comment by TalZa1810** [comment]
fails on visuals which are not related.

**Pull request merged**
