### PR TITLE
Add rtl/ltr to Storybook

### PR DESCRIPTION
**Pull request by EgoziE**
Added an addon that changes ltr/rtl of the page
Changed the name to `Wix Style React ${version}`

### CODE REVIEW

**Comment by shlomitc** [comment]
Can this be added to wix-storybook-utils? That way it can be a shared across all libraries

**Comment by argshook** [comment]
> Can this be added to wix-storybook-utils? That way it can be a shared across all libraries

technically yes, but because this is storybook version specific, i'm not sure `wix-storybook-utils` should be aligned to that.

but that's only a concern, it should be doable easily anyway

**Comment by shlomitc** [comment]
Why not align versions? I think it’s a proper do decide that since some major version, we support only storybook@5 versions

**Comment by argshook** [comment]
> Why not align versions? I think it’s a proper do decide that since some major version, we support only storybook@5 versions

at this moment all our libs are on storybook@5 but there's great chance it's wont be the case in future.

we can do this and try to sync versions but my hunch is that it could become problematic

for example, storybook@6 is released and we upgrade wix-ui-core to use
it, but the rest is still on storybook@5.

in such case wix-storybook-utils might work for storybook@5 but not storybook@6 and
we would also need to update/fix that.

anyway, i'm not against, just pondering if it's worth it

**Comment by shlomitc** [comment]
I think it worth it

**Comment by argshook** [comment]
added jira https://jira.wixpress.com/browse/DSM-79

**Pull request merged**
