### PR TITLE
Pin babel versions

### PR DESCRIPTION
**Pull request by EgoziE**

### CODE REVIEW

**Review by argshook — COMMENTED** [review]
you probably are aware, but make sure not to merge this, this json is from while lerna hasn't finished working

**Comment by EgoziE** [comment]
Oh so that was the problem with indentation... Okay good to know! thanks @argshook !

**Comment by EgoziE** [comment]
fixed it!
@jonathanadler FYI it's learna, not my webstorm

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6828/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6828

**Pull request merged**
