### PR TITLE
Update MessageBoxFunctionalLayout buttons type

### PR DESCRIPTION
**Pull request by malcolmmadsheep**
We use [react-intl](https://github.com/yahoo/react-intl) in our project for i18n and want to use `FormattedMessage` component it provides, but `string` type doesn't allow us to do it like for `title` property.

### CODE REVIEW

**Comment by lbelinsk** [comment]
@malcolmmadsheep it is a reasonable, but this is a breaking change.
any objection doing `oneOfType([node, string])` ?

**Comment by malcolmmadsheep** [comment]
@lbelinsk No objections. Just a question why not only `node` if it works also for strings. I firstly read [this article](https://reactjs.org/docs/typechecking-with-proptypes.html) about type checking with proptypes.

**Comment by argshook** [comment]
@lbelinsk @malcolmmadsheep i'd say `node` is perfectly fine and even preferable. shouldn't break current users as `string` is also `node`

**Comment by malcolmmadsheep** [comment]
@lbelinsk @argshook Can we merge it?

**Comment by argshook** [comment]
yep, i was waiting for build to pass, cause you never know.

do mind this will reach you after we release new version (sometime today)

**Comment by malcolmmadsheep** [comment]
Great. Thank you!

**Pull request merged**
