### PR TITLE
MessegeBox white theme

### PR DESCRIPTION
**Pull request by amitrch1**
## Motivation
the added white theme to the messege-box is required in the new Dashboard V2
in which a completed setup phase of the site is rewarded with a modal saying 'congrats...'
this is designed as having a white theme and is approved by UX.

## Changes
1. added white theme to messegebox header; 
2. closebutton for white theme should be "dark" themed
3. documented extra theme in markdown files of both modal and messegebox

### CODE REVIEW

**Comment by amitrch1** [comment]
sorry for the guestimation of who to ask a review from...

**Comment by amitrch1** [comment]
@shlomitc as I've put in the description of the PR,
i'm trying to add a white theme to the MessegeBox component, this means the changing of the header background and the X buttons' background.
this is required for a special announcement modal opening when finishing a phase in your site setup
(https://share.goabstract.com/afeeebca-ba8c-4cdd-9f75-f053e6ca85fc)

as i understand from what you wrote, i cannot add an example of the new theme because changing the "blue" theme breaks something

**Comment by shlomitc** [comment]
`MessageBox` is just the folder name, exposing `MessageBoxFunctionalLayout` and `MessageBoxMarketerialLayout`.
Considering both - which one of them are you trying to use?

I understand you're trying to add the white theme, that's clear from your PR. However, if there's an issue in the "blue" theme after your changes, then please do the required changes.

**Comment by amitrch1** [comment]
@shlomitc this is updated and can be reviewed now

**Comment by shlomitc** [comment]
@wuwa - can you please review?
https://wix-wix-style-react-pr-3127.surge.sh/?selectedKind=9.%20Modals&selectedStory=9.4%20Announcement&full=0&addons=0&stories=1&panelRight=0
image

**Comment by shlomitc** [comment]
@amitrch1 - please fix failing tests due to folder restructure so we can merge

**Comment by amitrch1** [comment]
pushed a fix for the directory changes (i think)
other than that i have no idea what is failing :) therefore, i have no idea how to fix it

**Comment by hepiyellow** [comment]
@amitrch1 @shlomitc 
I disabled the MessageBox Announcement - Celebratory test,
since it included an animated gif,
and causes flaky screenshot test.

@amitrch1 You are welcome to enable the test with a non-animated gif.

**Pull request merged**
