### PR TITLE
<Tag/> - add success theme [Testkit][Docs][Types]

### PR DESCRIPTION
**Pull request by ortroyaner**
### 🔦 Summary

New green color for 'Tag' component.

+ `theme` type can get `success` value.
+ added `isSuccessTheme` to drivers
+ updated colors storybook with the new purposes of `G30` & `G40`.

### ✅ Checklist

- [x] 👨‍🎨 UX change is approved by the Design System UX @milkyfruit 
- 📚 Change is documented
  - [x] Story
  - [x] Other - Colors page

### CODE REVIEW

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7018/

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7018

**Review by milkyfruit — APPROVED** [review]

**Comment by mykas** [comment]
@milkyfruit I don't see this theme in the zeplinc specs. Is this approved theme?

**Comment by milkyfruit** [comment]
> @milkyfruit I don't see this theme in the zeplin. Is this really ok?
It had a 'to do' task, now updated the spec: https://zpl.io/bzq6pJE

**Review by mykas — APPROVED** [review]
Good job! thank you

**Pull request merged**
