### PR TITLE
Color picker focus ring

### PR DESCRIPTION
**Pull request by urig-wix**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6838/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6838

**Review by jonathanadler — COMMENTED** [review]
Looks great!

Just notice that the component already has a [focus state](https://zeroheight.com/7sjjzhgo2/p/05a744-05-selections/t/313800).
Can you check with Johanna what the behaviour should be?

Also, note that the current focus state has a css transition:
```css
transition: box-shadow 0.1s linear;
```
which causes the focus ring to appear with an animation
https://bo.wix.com/pages/wix-ui-tpa.pr_6838/?path=/story/tests--colorpicker
Johanna should approve this as well.

Thanks!

**Review by jonathanadler — COMMENTED** [review]
Sorry got noticing only now 🤦 
But I think it would be better to move the `withFocusRing` to the ColorPicker itself, and not the item.
It would be easier for consumers to add the prop only once to the parent component, instead of adding it per item

**Review by jonathanadler — APPROVED** [review]
Amazing, thanks!

**Pull request merged**
