### PR TITLE
Component Generator - support generating component in beta

### PR DESCRIPTION
**Pull request by mykas**
This PR adds component generator infrastructure for Beta phase. It is part of initiative to move away from`upgrade` prop.

### CODE REVIEW

**Comment by argshook** [comment]
please don't merge yet

**Comment by mykas** [comment]
It is still in progress.

**Comment by shlomitc** [comment]
@argshook - what's the status of this PR?

**Comment by argshook** [comment]
@shlomitc this PR is as example of what currently needs to be done in
order to support beta components.

this involves a lot of duplication due to lack of some `wuf generate` configuration, namely `--output` flag.

TODO:
1. [ ] update `wuf generate` to support `--output` flag
2. [ ] use it in wix-style-react to support beta components
3. [ ] close this PR

**Comment by argshook** [comment]
pending PR https://github.com/wix/wix-style-react/pull/3589
closing this

**Pull request closed without merging**
