### PR TITLE
[WUT] - <DatePicker/> - Add role region and update the storybook example

### PR DESCRIPTION
**Pull request by sivanharel**
### 🔦 Summary

...

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-tpa**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_6798/

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-style-react**

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6798

**Review by nitayneeman — APPROVED** [review]
Not sure how it helps but I believe you do 😬

**Comment by sivanharel** [comment]
> Not sure how it helps but I believe you do 😬

I wanted to write in the description but forgot lol

Since Bookings don’t use the Year and Month dropdowns we are not going to fix the a11y gaps on the WSR dropdown component now and it will be fixed in the future as part of the a11y Dropdown task. (I opened a task for the wix-style-react team to fix the issue that we talked about: https://jira.wixpress.com/browse/DSM-1527).
So I removed the dropdowns from the a11y example and in order to show it for Neil.

**Comment by sivanharel** [comment]
I had a review with Neil and he asked me to add "role=region" for the wrapper div.
I also removed the ` placeholderText="Select A Date"` in the examples it was a mistake. This prop is relevant only for the DatePickerInput.

**Review by nitayneeman — APPROVED** [review]

**Pull request merged**
