### PR TITLE
be able to handle different mouse events

### PR DESCRIPTION
**Pull request by eyaleizenberg**
## Before you request a review, please make sure to check the following boxes:

- [x] Explain what has changed.
- [x] Explain why the change is needed.
- [ ] Added tests.
- [x] Update documentation.
- [x] Merge master with no conflicts.
- [x] Make sure the build is passing on ci.
- [ ] If this pr closes any issue, please add a github link to close it.
- [ ] If you changed something in the product design/UX, you got the approval of [Ben Benhorin](https://wix.slack.com/messages/@benb).

### CODE REVIEW

**Comment by argshook** [comment]
@eyaleizenberg please cover at least few of the `Before you request a review, please make sure to check the following boxes`

why is this needed, what is it you try to do?

**Comment by eyaleizenberg** [comment]
@argshook 
This PR allows the Drill Menu to response to `onMouseDown` events instead of just `onClick`, shaving about 200ms in perceived performance. By default, the events are still `onClick`, but you can pass the `onMouseDown` instead.

**Comment by eyaleizenberg** [comment]
@argshook We don't need any of this 'accessibility' in the sidebar drill. We much rather gains the performance and start navigation when the mouse is down and not up.

**Comment by argshook** [comment]
we do care about accessibility.
currently it's far from perfect but this change makes it even worse.
this also adds more overhead than it solves.

if there are real performance issues, they should be solved where bottleneck is, surely time between `mouseDown` and `mouseUp` is not it. this is a workaround, not a solution.

sorry, no i can't allow this.

**Pull request closed without merging**
