### PR TITLE
fix: make WSR polyfills run in SSR without reference errors

### PR DESCRIPTION
**Pull request by zivl**
Added checks for presence of `window` and `document` in WSR polyfills

Fixing issue where running WSR polyfills under SSR project and `window` or `document` is not defined, as described here:
https://wix.slack.com/archives/C39FTGUBZ/p1572856384039200

@assafganor

### CODE REVIEW

**Comment by assafganor** [comment]
@shlomitc  
It is blocking us.
Can you please prioritize this PR?

**Comment by shlomitc** [comment]
@mykas can you please take a look?

**Comment by assafganor** [comment]
@mykas  can you please?

**Comment by assafganor** [comment]
@mykas  when will it be released?

**Comment by mykas** [comment]
It is already released

**Pull request merged**
