### PR TITLE
update(storybook): use babel-loader:7 in storybook config and update deps

### PR DESCRIPTION
**Pull request by mykas**
Stable storybook. Finally.

### CODE REVIEW

**Comment by shlomitc** [comment]
as we're not transpiling with babel-7, wouldn't be a problem installing it alongside yoshi?
@yavorsky - any thoughts about this?

**Comment by mykas** [comment]
babel-loader is not babel-7. Yoshi uses babel-loader 7. Issues started to happened with stable storybook, because storybook 4.1 has dependency of babel-loader@8

**Comment by mykas** [comment]
screenshot 2019-01-31 at 17 05 59

**Comment by mykas** [comment]
What I did is basically forced storybook to use babel-loader@7

**Comment by yavorsky** [comment]
Yeah, babel-loader@7 works with babel@6. Anyway, it shouldn't break something, since `yoshi` will use own babel-loader.

**Comment by yavorsky** [comment]
I'm preparing PR to migrate to babel@7 the whole project. But we need to update yoshi to 4 (since `yoshi test --protractor` requires babel-register@6) or run e2e w/o yoshi (which is also good option in long-term perspective).

**Pull request merged**
