### PR TITLE
<Barchart /> - fix labelShort when there is descriptionInfo

### PR DESCRIPTION
**Pull request by maxvektor**
### 🔦 Summary
...

### ✅ Checklist
- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

**Comment by mykas** [comment]
Can you explain a bit what does it do? Show me some screenshots of whats was wrong and whats fixed?

**Comment by maxvektor** [comment]
without this fix it always sows small text when there is a `discriptionInfo`. 
Before:
Screen Shot 2019-10-03 at 1 22 05 PM
There is enough space, but it shows `shortLabel`

Now like this:
Screen Shot 2019-10-03 at 1 21 16 PM

**Comment by maxvektor** [comment]
Without `descriptionInfo` it works fine so I missed this state during development.

**Comment by mykas** [comment]
I think it would be great if you could cover this with `.visual` tests.

**Comment by maxvektor** [comment]
@mykas 
It is covered:
https://github.com/wix/wix-style-react/pull/4183/files#diff-5b0ba9faf0cf3eef0763f3bd005a5d2cR163

**Comment by mykas** [comment]
oh ok, sorry missed that.

**Pull request merged**
