### PR TITLE
Migrated some of the internal icons to wix-ui-icons-common

### PR DESCRIPTION
**Pull request by alisey**
Migrated the following components to wix-ui-icons-common:

* Breadcrumbs (divider)
* Checkbox (checked and indeterminate)
* Input (error icon)
* Input (spinners in TimePicker)
* InputArea (error icon)
* MessageBox (close icon)
* RichTextArea (error icon)

---

- [x] Change is tested
- [x] Change is documented
- [x] Build is green
- [x] Change of UX is approved by [wuwa](https://github.com/wuwa) or [milkyfruit](https://github.com/milkyfruit)

### CODE REVIEW

**Comment by alisey** [comment]
@wuwa can you please check that affected components look good? They're listed in the top comment. Storybook: https://wix-wix-style-react-pr-1616.surge.sh

**Comment by wuwa** [comment]
@alisey all look good. only one i couldn't manage to see is "Input (spinners in TimePicker)"

**Comment by alisey** [comment]
@wuwa up and down arrows inside of the TimePicker.

Before:
image

After:
image

In both examples they're offset by 1 pixel to the top, that's a style applied to all input suffixes, and I wasn't sure I wouldn't accidentally break something if I changed it.

**Comment by wuwa** [comment]
@alisey they should actually move 1px down

**Pull request merged**
