### PR TITLE
release/4.2.0

### PR DESCRIPTION
**Pull request by shlomitc**

### CODE REVIEW

**Comment by argshook** [comment]
dank

**Comment by shlomitc** [comment]
we're ok here, but the thing is that the new [`AddItem`](https://wix-wix-style-react-pr-1829.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.12%20AddItem&full=0&addons=0&stories=1&panelRight=0) component is not complete.
It is a refactored version of the `ImageViewer`, but the ratio features (which is what we really wanted), is here and not merged yet:
https://github.com/wix/wix-style-react/pull/1822

few options:
1. release it as it is.
2. wait for PR to be merged
3. move the AddItem to `experimental` section in the storybook

**Comment by lbelinsk** [comment]
@shlomitc if Shai will take care of this pr today, will it be ok to merge, or are we missing more stuff for the AddItem?
@shaibv said he will take care of it today

**Comment by shlomitc** [comment]
`AddItem` PR was merged, going to release soon

**Pull request merged**
