### PR TITLE
animate the entrance of the pageHeader

### PR DESCRIPTION
**Pull request by mosheKerbel**
fix issue - https://github.com/wix/wix-style-react/issues/3209

### CODE REVIEW

**Comment by mosheKerbel** [comment]
@wuwa 
this PR handles this issue https://github.com/wix/wix-style-react/issues/3209
now when you scroll and the page header gets "sticky", it enters with an effect of
opacity + slide in from bottom.
i put the animation to take 0.2s.
could you take a look here and say if it looks good enough?
https://wix-wix-style-react-pr-3230.surge.sh/?selectedKind=2.%20Layout&selectedStory=2.1%20Page%20Layout&full=0&addons=0&stories=1&panelRight=0

**Comment by wuwa** [comment]
can you please make y movement smaller distance - from y+20 --> y

**Comment by mosheKerbel** [comment]
@wuwa the animation was on the x axis, so i changed it from 50 to 20...
did i got you right?

**Comment by wuwa** [comment]
yes, looks good. it is y axis (top property)

**Comment by mosheKerbel** [comment]
we are good to go from Ben's side.
@hepiyellow

**Comment by hepiyellow** [comment]
@wuwa 
BTW: I had an idea, that we can make the `actionsBar` sticky, so it won't be so "jumpy", it will simply stick.

### actionsBar needs to be fixed.

Today we pass `minimized` argument to the `actuiosBar`, so consumers can render it differently when minimized.

I we remove the `minimized` argument, then the actionsBar will be the same in both cases, and then sticky will work just fine.

**Pull request merged**
