### PR TITLE
test storybook 4.1.0-alpha.8

### PR DESCRIPTION
**Pull request by ranyitz**
### What changed

Update storybook version that should support react 15.

### Why it changed

After storybook version was pinned in wsr to - https://github.com/wix/yoshi/commit/0338873c49b3cb2ef2f53460307cbe9bc02e2039

They've released a new version that will attempt to support all versions of react. We're opening this PR to see whether it will work for us.

### context
https://github.com/storybooks/storybook/issues/4191#issuecomment-441388216

---

- [ ] Build is green

### CODE REVIEW

**Comment by shlomitc** [comment]
I tried to run it locally and it fails both on `npm run storybook` (dev) and `npm run storybook:buld` (deployable build).

it fails for this error
```bash
/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/@storybook/core/dist/server/build-static.js:67
      if (stats.hasErrors()) {
                ^

TypeError: Cannot read property 'hasErrors' of undefined
    at run (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/@storybook/core/dist/server/build-static.js:67:17)
    at finalCallback (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/Compiler.js:210:39)
    at onCompiled (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/Compiler.js:218:20)
    at hooks.make.callAsync.err (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/Compiler.js:542:21)
    at _err1 (eval at create (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:28:1)
    at _addModuleChain (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/Compilation.js:1081:13)
    at processModuleDependencies.err (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/Compilation.js:1004:25)
    at asyncLib.forEach.err (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/Compilation.js:918:13)
    at /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:2825:7
    at /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:2825:7
    at done (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:2859:11)
    at /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:2813:7
    at asyncLib.forEach.err (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/Compilation.js:918:13)
    at /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:2825:7
    at /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:2825:7
    at done (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:2859:11)
```

`stats`, which is the result after webpack running the `managerConfig` comes out undefined. not sure why...
https://github.com/storybooks/storybook/blob/next/lib/core/src/server/build-static.js#L37

I changed it to `if (stats && stats.hasErrors()) {` to make it pass, so build now finishes, but the `index.html` file is not created. The iframe does however and is functional.

Will update if I have further info

**Comment by shlomitc** [comment]
some more debugging, I logged the webpack error and found this. looks like webpack can't resolve React for some reason

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react/lib/React' in '/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react-dom/lib'
    at factory.create (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:2825:7
    at /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'react/lib/React' in '/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react-dom/lib'
  Parsed request is a module
  using description file: /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react-dom/package.json (relative path: ./lib)
    aliased with mapping 'react': '/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/react.js' to '/Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/react.js/lib/React'
      using description file: /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react-dom/package.json (relative path: ./lib)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/package.json (relative path: ./react.js/lib/React)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/react.js/lib/React doesn't exist
          .mjs
            Field 'browser' doesn't contain a valid alias configuration
            /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/react.js/lib/React.mjs doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/react.js/lib/React.js doesn't exist
          .jsx
            Field 'browser' doesn't contain a valid alias configuration
            /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/react.js/lib/React.jsx doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/react.js/lib/React.json doesn't exist
          as directory
            /Users/shlomitc/WebstormProjects/wix-style-react/node_modules/react/react.js/lib/React doesn't exist
```

**Comment by ranyitz** [comment]
@Frankcarvajal @shlomitc I've opened a PR that should help with seeing the real error - https://github.com/storybooks/storybook/pull/4883

After some digging around, I've found the problem.

[In this change](https://github.com/storybooks/storybook/commit/fdb673d8311d590023cfd82ab5e433e41a14fa87) you've added a dependency to `react@16` & `react-dom@16` on the **react** package, while the `require.resolve` is actually from the **core** package.

The **react** and the **core** packages installed side by side in `node_modules/@storybook` and if the user has its own react version, which is different than the one specified in `@storybook/react` It will be installed inside of `node_modules/@storybook/react/node_modules/react`.

Which means that the react version that the manager gets is the user version, in our case react@15, which is not the wanted behavior.

______________________

A proposed solution will be to start resolving to react from the `@storybook/react` package using something like https://github.com/sindresorhus/resolve-from.

**Comment by shlomitc** [comment]
closing due to inactivity.
for now, we will keep using the fixed version

**Pull request closed without merging**
