### PR TITLE
Major Version 2.0.0

### PR DESCRIPTION
**Pull request by shlomitc**
Merge here all relevant breaking changes

### CODE REVIEW

**Comment by lbelinsk** [comment]
@shlomitc maybe let's add the Badge breaking changes?
It is merged in wix-ui-backoffice, just needs Ben approval

**Comment by lbelinsk** [comment]
Also Grid

**Comment by lbelinsk** [comment]
So about Grid span=12 by default breaking change, this pr is approved. We can merge it whenever we want:
https://github.com/wix/wix-style-react/pull/1279#pullrequestreview-85281535

**Comment by shlomitc** [comment]
@lbelinsk - we can merge as long as it's approved and can be merged until tomorrow.

**Comment by lbelinsk** [comment]
It is approved. can merge it tomorrow

**Pull request merged**
