### PR TITLE
<StatisticsWidget/> - updated description style for size tiny

### PR DESCRIPTION
**Pull request by yogevitz**
### 🔦 Summary

updated description style for size tiny

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [x] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
- 🔬 Change is tested
  - [x] Component

### CODE REVIEW

**Comment by shlomitc** [comment]
Hey!
1. please take a minute to sign your commits in order for them to pass in the CI. https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits
2. are these changes reflected in the official Zeplin specs? https://zpl.io/a87vGwJ. if not, who from the design system approved it?

**Comment by yogevitz** [comment]
Hey @shlomitc
1. I added the key 🔑
2. The changes were approved by @milkyfruit here: https://wix.monday.com/boards/535450707/pulses/719698905/posts/778374679

Thanks :)

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://www.wix.com/pages/wix-style-react.pr_5933/

**Comment by shlomitc** [comment]
This is the visual difference:
Before:
image
After:
image

@milkyfruit - is that approved by you?
Also, @yogevitz - can you please extend the visual test with the `description` content so it will also cover this use case?
thanks

**Comment by yogevitz** [comment]
@shlomitc added 👍

**Review by milkyfruit — APPROVED** [review]
@yogevitz @shlomitc Yes, this is what I instructed the team to do. Specs will be updated afterwards.

**Pull request merged**
