### PR TITLE
<SidebarSectionItem/> [Testkit] - add `isSelected()` and `isDisabled()` methods

### PR DESCRIPTION
**Pull request by Romms**
### 🔦 Summary

Add `isSelected()` and `isDisabled()` methods to `<SidebarSectionItem/>` testkit
### ✅ Checklist

- [ ] ~~👨‍💻 API change is approved by the UI Infra Developers~~
- [ ] ~~👨‍🎨 UX change is approved by the Design System UX~~
- 📚 Change is documented
  - [ ] ~~Story~~
  - [ ] ~~API description~~
  - [ ] ~~Cheatsheet~~
  - [ ] ~~Other (explain)~~
- 🔬 Change is tested
  - [x] Component
  - [ ] ~~Visual test~~

### CODE REVIEW

**Comment by mykas** [comment]
Please sign your commits with GPG key in order for builds to work: https://github.com/wix/wix-style-react/blob/master/packages/wix-style-react/docs/contribution/CREATE_PR.md

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-tpa**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-tpa.pr_7068/

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-style-react**

You can find it under one of the following URLs:
* https://preview.wix-style-react.com/pr_7068

**Review by mykas — APPROVED** [review]
Good job! Nicely done

**Pull request merged**
