### PR TITLE
`<Notification/>`- animating notification

### PR DESCRIPTION
**Pull request by TalZa1810**
### 🔦 Summary
Considering that most notifications are not higher than 72px. 
Resolves https://github.com/wix/wix-style-react/issues/4922

### ✅ Checklist

- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Cheatsheet
  - [ ] Other (explain)
- 🔬 Change is tested
  - [x] Component
  - [x] Visual test

### CODE REVIEW

**Comment by TalZa1810** [comment]
@ZilvinasMaciulis 
I've updated the timing for the entering. Just make sure it's fine on your end :)

**Comment by ZilvinasMaciulis** [comment]
@TalZa1810 is there still time to change the easing? Sorry for the last minute but I just realized that bottom, content is not leaving the screen, therefore, we should use 0.4 , 0 , 0.2 , 1 easing value for both show and hide animations. Sorry

**Comment by TalZa1810** [comment]
@ZilvinasMaciulis 
I've updated the animations and used variables where needed:
https://github.com/wix/wix-style-react/blob/f70d6522b7f7f51938529c1d0db3f08c176a00bf/src/Notification/Notification.st.css#L6

https://github.com/wix/wix-style-react/blob/f70d6522b7f7f51938529c1d0db3f08c176a00bf/src/Notification/Notification.st.css#L104

**Comment by TalZa1810** [comment]
using `<Animator/>` instead of css for calculating height dynamically.

**Pull request closed without merging**
