### PR TITLE
remove yoshi webpack config from `npm run autotools` & `npm run storybook:visual`

### PR DESCRIPTION
**Pull request by argshook**
this PR makes removes yoshi webpack config from:

* `npm run sanity`
* `npm run storybook:visual`

Instead of yoshi webpck config, we use local one.
This is for an ongoing effort to remove the usage of yoshi.

---

The webpack config is not invented on my own, it is taken from yoshi with only relevant parts included. It's not as big and bulky as one might have thought :)

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://preview.wix-style-react.com/pr_6033

**Review by EgoziE — APPROVED** [review]
Looks good.
I'd replace `lodash/merge` with spread or Object.assign, but it doesn't really matter.

**Comment by argshook** [comment]
as discussed, while we're investigating the capabilities of currently experimental yoshi-library-flow, this PR can be merged.

**Comment by argshook** [comment]
> Looks good.
> I'd replace `lodash/merge` with spread or Object.assign, but it doesn't really matter.

i used `lodash/merge` to remain consistent with other configs that we have and also cause it does a deep merge, with native `Object.assign` i'd need to do more tricks.

**Pull request merged**
